### ISSUE TITLE
Rake task (purge) not supported by 'oracle_enhanced' adapter

### ISSUE THREAD

**Issue by roooodcastro** [rsim/oracle-enhanced#1039]
I'm building a "gemifyed" module for a group of similar applications to centralize some core models. I created the gem by running:

    rails plugin new my_gem_name -T --mountable --full --dummy-path=spec/dummy

However, whenever I run rspec with rake or any other rake task involving the DB, I get this error. I read #49 but it doesn't seem related, as I'm correctly requiring the gem:

In my `.gemspec` file I have the dependencies specified correctly as far as I know:

    s.add_runtime_dependency 'activerecord-oracle_enhanced-adapter', '~> 1.6.7'
    s.add_runtime_dependency 'rails', '~> 4.2'
    s.add_runtime_dependency 'ruby-oci8', '~> 2.1.8'

I also can run the tests correctly if I run with `rake app:spec`, but the same error pops up at the start, and oddly enough the tests successfully run even with the error, even the ones that write/read the DB.

What I can't do is run any useful rake tasks, such as `rake app:db:test:prepare`, which is necessary as we have a legacy schema that doesn't use migrations.

The complete error is the following:

    > rake app:db:test:prepare --trace

    ** Invoke load_app (first_time)
    ** Execute load_app
    ** Invoke app:db:test:prepare (first_time)
    ** Invoke app:environment (first_time)
    ** Execute app:environment
    ** Invoke app:db:load_config (first_time)
    ** Execute app:db:load_config
    ** Execute app:db:test:prepare
    ** Invoke app:db:test:load (first_time)
    ** Invoke app:db:test:purge (first_time)
    ** Invoke app:environment 
    ** Invoke app:db:load_config 
    ** Execute app:db:test:purge
    rake aborted!
    ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'oracle_enhanced' adapter
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:264:in `class_for_adapter'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:164:in `purge'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:356:in `block (3 levels) in <top (required)>'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
    /home/rodrigo/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
    /home/rodrigo/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:362:in `block (3 levels) in <top (required)>'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
    /home/rodrigo/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/bin/rake:23:in `load'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/bin/rake:23:in `<main>'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/bin/ruby_executable_hooks:15:in `eval'
    /home/rodrigo/.rvm/gems/ruby-2.3.1@my_gem_name/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => app:db:test:load => app:db:test:purge

I believe this is an issue with the require order or something, but I tried fixing it by putting `require 'activerecord-oracle_enhanced-adapter'` everywhere where it should make a difference (spec_helper, dummy/config/application.rb, etc) and still didn't fix it, so I'm out of ideas here.

**Comment by roooodcastro** [comment]
So uh, this is awkward, but I already managed to "fix" the error by adding the gem declaration to the Gemfile, duplicating the gemspec's declaration. My .gemspec is unchanged, and gemfile now looks like this:

    source 'https://rubygems.org'

    gemspec

    gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.7'

I'm closing this now, but I still feel there's something odd here that probably have a better explanation and fix than this hack I made.
