### ISSUE TITLE
ArgumentError: invalid value for BigDecimal(): "1.E+00" using ruby 2.4.0rc1

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1085]
* Environment

```
ActiveRecord Oracle enhanced adapter: `rails51` branch
ActiveRecord: `master` branch
Oracle database 12.1.0.2
ruby-oci8 (2.2.2)
```

* Steps to reproduce:

```ruby
$ cd oracle-enhanced
$ git checkout rails51
$ bundle install
$ rake spec
Resolving dependencies...
==> Loading config from ENV or use default
==> Running specs with MRI version 2.4.0
/home/yahonda/.rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/bundler/gems/ruby-oci8-d3a1a3dedde6/lib/oci8/bindtype.rb:206: warning: constant ::Fixnum is deprecated
/home/yahonda/.rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/bundler/gems/ruby-oci8-d3a1a3dedde6/lib/oci8/bindtype.rb:209: warning: constant ::Bignum is deprecated
/home/yahonda/.rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/bundler/gems/ruby-oci8-d3a1a3dedde6/lib/oci8/compat.rb:73: warning: constant ::Fixnum is deprecated
/home/yahonda/.rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:206: warning: constant ::Fixnum is deprecated
/home/yahonda/.rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:230: warning: constant ::Fixnum is deprecated
==> Effective ActiveRecord version 5.1.0.alpha
/home/yahonda/.rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:230: warning: constant ::Fixnum is deprecated
rake aborted!
ArgumentError: invalid value for BigDecimal(): "1.E+00"
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:409:in `ping'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:74:in `ping'
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:432:in `active?'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:431:in `verify!'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:796:in `block in checkout_and_verify'
/home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:811:in `_run_checkout_callbacks'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `checkout_and_verify'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:919:in `retrieve_connection'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/home/yahonda/git/rails/activerecord/lib/active_record/connection_handling.rb:88:in `connection'
/home/yahonda/git/oracle-enhanced/Rakefile:27:in `block in <top (required)>'
Tasks: TOP => spec => clear
(See full trace by running task with --trace)
$
```

It does not reproduce with `ruby 2.4.0preview3`.
```
$ ruby -v
ruby 2.4.0preview3 (2016-11-07 trunk 56661) [x86_64-linux]
```

**Comment by yahonda** [comment]
Closed as kubo/ruby-oci8#144 has been merged.
