### ISSUE TITLE
ArgumentError: invalid value for BigDecimal(): "1.E+00"

### ISSUE THREAD

**Issue by sumantacaptain** [rsim/oracle-enhanced#1137]
Hi, I am using Ruby 2.4 and Rails 5.0.1. 

I have Included 
**gem 'ruby-oci8', '~>2.2.2'** & 
**gem 'activerecord-oracle_enhanced-adapter'**  in my Gemfile. 

I just scaffolded User : **rails generate scaffold User name:string title:string**

and tried to migrate it: -
 **rake db:migrate**

But got the below mentioned error. **Any help will be appreciated.** 

```ruby
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
Warning: NLS_LANG is not set. fallback to US7ASCII.
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/bindtype.rb:206: warning: constant ::Fixnum is deprecated
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/bindtype.rb:209: warning: constant ::Bignum is deprecated
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/compat.rb:73: warning: constant ::Fixnum is deprecated
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
rake aborted!
ArgumentError: invalid value for BigDecimal(): "1.E+00"
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/bindtype.rb:35:in `BigDecimal'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/bindtype.rb:35:in `to_d'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/bindtype.rb:35:in `get'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:547:in `get_data'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:547:in `block in fetch_one_row_as_array'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:546:in `collect'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:546:in `fetch_one_row_as_array'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:149:in `fetch'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/oci8.rb:280:in `exec_internal'
/home/srikanth/.rvm/gems/ruby-2.4.0@approve/gems/ruby-oci8-2.2.2/lib/oci8/oci8.rb:267:in `exec'
```

**Comment by koic** [comment]
Thanks for the report.

This problem was resolved https://github.com/kubo/ruby-oci8/pull/144. And ruby-oci8 (2.2.3) includes this patch.

https://rubygems.org/gems/ruby-oci8/versions/2.2.3.

Could you please use ruby-oci8 (2.2.3) ?

Thanks.

**Comment by sumantacaptain** [comment]
Thanks a lot Koic.... solved! You are my star!

**Comment by koic** [comment]
@sumantacaptain I'm glad the problem was solved 😃
