### ISSUE TITLE
add_column gets `ArgumentError: wrong number of arguments (given 2, expected 1)`

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1157]
### Environment:

- Rails master branch
- Oracle enhanced adapter master branch
- Ruby 2.3.3 (also it reproduces with Ruby 2.4.0)
- Oracle Database 12.1.0.2

### Error 1

```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/migration/column_attributes_test.rb -n test_add_column_newline_default
Using oracle
... snip ...
Run options: -n test_add_column_newline_default --seed 33485

# Running:

E

Finished in 0.150591s, 6.6405 runs/s, 0.0000 assertions/s.

  1) Error:
ActiveRecord::Migration::ColumnAttributesTest#test_add_column_newline_default:
ArgumentError: wrong number of arguments (given 2, expected 1)
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:9:in `quote'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/structure_dump.rb:276:in `add_column_options!'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:259:in `add_column'
    /home/yahonda/git/rails/activerecord/test/cases/migration/helper.rb:36:in `add_column'
    test/cases/migration/column_attributes_test.rb:12:in `test_add_column_newline_default'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### Error 2 (actually this is a side effect of error1 when it attempts to drop columns failed to create by `add_column` )

```ruby
$ ARCONN=oracle bundle exec ruby -w -Itest test/cases/locking_test.rb -n test_decrement_counter_updates_custom_lock_version
Using oracle
... snip ...
Run options: -n test_decrement_counter_updates_custom_lock_version --seed 28724

# Running:

E

Finished in 0.436093s, 2.2931 runs/s, 0.0000 assertions/s.

  1) Error:
OptimisticLockingWithSchemaChangeTest#test_decrement_counter_updates_custom_lock_version:
ActiveRecord::StatementInvalid: OCIError: ORA-00904: "TEST_COUNT": invalid identifier: ALTER TABLE "LEGACY_THINGS" DROP COLUMN "TEST_COUNT" CASCADE CONSTRAINTS
    stmt.c:243:in oci8lib_230.so
    /home/yahonda/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.3/lib/oci8/cursor.rb:129:in `exec'
    /home/yahonda/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.3/lib/oci8/oci8.rb:276:in `exec_internal'
    /home/yahonda/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.3/lib/oci8/oci8.rb:267:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:443:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:90:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:605:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:598:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1050:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `execute'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:326:in `remove_column'
    test/cases/locking_test.rb:479:in `remove_counter_column_from'
    test/cases/locking_test.rb:493:in `ensure in counter_test'
    test/cases/locking_test.rb:493:in `counter_test'
    test/cases/locking_test.rb:437:in `block (2 levels) in <class:OptimisticLockingWithSchemaChangeTest>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by yahonda** [comment]
Working on these errors at [rails51_refactor_add_column](https://github.com/yahonda/oracle-enhanced/tree/rails51_refactor_add_column) branch. still there is a regression in this branch.

```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:1165
... snip ...
F

Failures:

  1) OracleEnhancedAdapter schema definition virtual columns should add virtual column
     Failure/Error: at.add_column(column_name, type, options)
     
     NoMethodError:
       undefined method `to_sym' for nil:NilClass
     # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb:416:in `add_column'
     # ./lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:257:in `add_column'
     # /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:851:in `block in method_missing'
     # /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:820:in `block in say_with_time'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
     # /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:820:in `say_with_time'
     # /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:840:in `method_missing'
     # ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:1167:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:114:in `instance_eval'
     # ./spec/spec_helper.rb:114:in `block (2 levels) in schema_define'
     # /home/yahonda/git/rails/activerecord/lib/active_record/migration.rb:828:in `suppress_messages'
     # ./spec/spec_helper.rb:113:in `block in schema_define'
     # /home/yahonda/git/rails/activerecord/lib/active_record/schema.rb:48:in `instance_eval'
     # /home/yahonda/git/rails/activerecord/lib/active_record/schema.rb:48:in `define'
     # /home/yahonda/git/rails/activerecord/lib/active_record/schema.rb:44:in `define'
     # ./spec/spec_helper.rb:112:in `schema_define'
     # ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:1166:in `block (3 levels) in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `instance_exec'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:254:in `block in run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `block in with_around_and_singleton_context_hooks'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `block in with_around_example_hooks'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `block in run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/hooks.rb:464:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:453:in `with_around_example_hooks'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:496:in `with_around_and_singleton_context_hooks'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example.rb:251:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `map'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:589:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `block in run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `map'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:590:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (3 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `map'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:113:in `block (2 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1835:in `with_suite_hooks'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/reporter.rb:77:in `report'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:111:in `run_specs'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:87:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.0/bin/rspec:22:in `load'
     # /home/yahonda/.rbenv/versions/2.4.0/bin/rspec:22:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `load'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli/exec.rb:27:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:335:in `exec'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
     # /home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
     # /home/yahonda/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'

Finished in 0.19734 seconds (files took 0.87701 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb:1165 # OracleEnhancedAdapter schema definition virtual columns should add virtual column

Coverage report generated for RSpec to /home/yahonda/git/oracle-enhanced/coverage. 854 / 1849 LOC (46.19%) covered.
$
```
