### ISSUE TITLE
Test 3-level DB configs with Oracle enhanced adapter

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1214]
rails/rails#28095

I am not 100% sure if this reproduce test case is correct, but at least I was able to generate similar error 
then open an issue here.

```
`resolve_symbol_connection': 'readonly' database is not configured. Available: ["common"] (ActiveRecord::AdapterNotSpecified)
```

#### Environments:
```
Rails 5.1.0.beta1
Oracle enhanced adapter 1.8.0.beta1
Oracle Database 12.1.0.2 Enterprise Edition
ruby 2.5.0dev (2017-02-28 trunk 57744) [x86_64-linux]
```

#### Steps to reproduce:

```ruby

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  #gem "rails", github: "yahonda/rails", branch: "v5.1.0.beta1_rep28095"
  gem "rails", "~> 5.1.0.beta"
  gem "activerecord-oracle_enhanced-adapter", "~> 1.8.0.beta1"
  gem "ruby-oci8"
  gem "byebug"
end

require "active_record"
require "logger"
require "active_record/connection_adapters/oracle_enhanced_adapter"
require "pp"

ENV["RAILS_ENV"] = "default_env"

@handler = ActiveRecord::ConnectionAdapters::ConnectionHandler.new

config = {
  "default_env" => {
    "readonly" => { "adapter" => "oracle_enhanced",
                    "database" => "ORCLPDB1",
                    "host" => "localhost",
                    "port" => 1521,
                    "username" => "oracle_enhanced_schema",
                    "password" => "oracle_enhanced_schema" },
    "primary"  => { "adapter" => "oracle_enhanced",
                    "database" => "ORCLPDB1",
                    "host" => "localhost",
                    "port" => 1521,
                    "username" => "oracle_enhanced",
                    "password" => "oracle_enhanced" },
  },
  "common" => { "adapter" => "oracle_enhanced",
                "database" => "ORCLPDB1",
                "host" => "localhost",
                "port" => 1521,
                "username" => "system",
                "password" => "admin" }
}

ActiveRecord::Base.configurations = config
ActiveRecord::Base.logger = Logger.new(STDOUT)

@handler.establish_connection(:common)
@handler.establish_connection(:readonly)
@handler.establish_connection(:primary)

pool_common   = @handler.retrieve_connection_pool("common")
pool_readonly = @handler.retrieve_connection_pool("readonly")
pool_primary  = @handler.retrieve_connection_pool("primary")
pp pool_common.inspect
pp pool_readonly.inspect
pp pool_primary.inspect
```

#### Expected behavior:
it should show each connection information

#### Actual behavior:

It shows `'readonly' database is not configured. Available: ["common"] (ActiveRecord::AdapterNotSpecified)`

```ruby
$ ruby rep.rb
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.1
Using minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubi 1.6.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 2.0.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 8.0.0
Using ruby-plsql 0.6.0
Using bundler 1.14.5
Using byebug 9.0.6
Using method_source 0.8.2
Using thor 0.19.4
Using ruby-oci8 2.2.3
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using sprockets 3.7.1
Using websocket-driver 0.6.5
Using mime-types 3.1
Using activesupport 5.1.0.beta1
Using loofah 2.0.3
Using mail 2.6.4
Using rails-dom-testing 2.0.2
Using globalid 0.3.7
Using activemodel 5.1.0.beta1
Using rails-html-sanitizer 1.0.3
Using activejob 5.1.0.beta1
Using activerecord 5.1.0.beta1
Using actionview 5.1.0.beta1
Using activerecord-oracle_enhanced-adapter 1.8.0.beta1
Using actionpack 5.1.0.beta1
Using actioncable 5.1.0.beta1
Using actionmailer 5.1.0.beta1
Using railties 5.1.0.beta1
Using sprockets-rails 3.2.0
Using rails 5.1.0.beta1
        from rep.rb:53:in `<main>'
        from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/abstract/connection_pool.rb:878:in `establish_connection'
        from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/connection_specification.rb:180:in `spec'
        from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/connection_specification.rb:141:in `resolve'
        from /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/connection_specification.rb:227:in `resolve_connection'
/home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/activerecord-5.1.0.beta1/lib/active_record/connection_adapters/connection_specification.rb:246:in `resolve_symbol_connection': 'readonly' database is not configured. Available: ["common"] (ActiveRecord::AdapterNotSpecified)
$
```

**Comment by yahonda** [comment]
@deepj Would you give it a try using this Gemfile entry and update this issue if you still reproduces `ActiveRecord::AdapterNotSpecified ('development' database is not configured. Available: ["default", "test", "staging", "primary", "migration"]):` 


```ruby
 gem "rails", github: "yahonda/rails", branch: "v5.1.0.beta1_rep28095"
```

This branch has a diagnose commit which has side effects, I do not think it will break databases but please test at some development environment.

Thanks.

**Comment by yahonda** [comment]
@deepj Thanks for the comment at https://github.com/rails/rails/pull/28095#issuecomment-293797148 .
If I understand it correctly 3-level DB configuration is working using Oracle enhanced adapter without using "v5.1.0.beta1_rep28095" branch.

Let me close this issue since this test case may not be the right one.
