### ISSUE TITLE
Time type support status

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1275]
I'd like to explain current ActiveRecord `Time` support with Oracle database.
`Time` is defined but it does not work as expected with Oracle enhanced adapter.

### Symptoms

* `t.time` in `create_table` will be created as Oracle `TIMESTAMP` sql type,
which also stores year, month and date information.

* Oracle `TIMESTAMP` sql type is also associated with Rails `datetime` type
then schema dumper will generate this column as `datetime`, not `time`.

* Oracle `TIMESTAMP` default precision is 6, then schema dumper generates `precision: 6`
even if this migration did not specify any precision.

### Background

* Rails `Time` type is associated with `time` sql type at PostgreSQL and MySQL databases. 
Oracle database does not.

* ActiveRecord maps each SQL type with Rails type at `initialized_type_map` method.

```ruby
          register_class_with_precision m, %r(time),      Type::Time
```

Then any sql type whose name matches `%r(time)i` condition will be mapped to Rails `Time` type.
`TIMESTAMP`, `TIMESTAMP WITH TIME ZONE` and `TIMESTAMP WITH LOCAL TIME ZONE`.

### ActiveRecord unit test failures due to Time type support

```ruby
16) Error:
SchemaDumperDefaultsTest#test_schema_dump_defaults_with_universally_supported_types:
ActiveRecord::StatementInvalid: OCIError: ORA-01843: not a valid month: CREATE TABLE "DUMP_DEFAULTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "STRING_WITH_DEFAULT" VARCHAR2(255) DEFAULT 'Hello!', "DATE_WITH_DEFAULT" DATE DEFAULT '2014-06-05', "DATETIME_WITH_DEFAULT" TIMESTAMP DEFAULT '2014-06-05 07:17:04', "TIME_WITH_DEFAULT" TIMESTAMP DEFAULT '07:17:04', "DECIMAL_WITH_DEFAULT" DECIMAL(20,10) DEFAULT '1234567890.0123456789')
    stmt.c:243:in oci8lib_250.so
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.3/lib/oci8/cursor.rb:129:in `exec'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.3/lib/oci8/oci8.rb:276:in `exec_internal'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.3/lib/oci8/oci8.rb:267:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:429:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:90:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/monitor.rb:214:in `mon_synchronize'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1037:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `execute'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:76:in `create_table'
    /home/yahonda/git/rails/activerecord/test/cases/schema_dumper_test.rb:425:in `block in <class:SchemaDumperDefaultsTest>'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:413:in `instance_exec'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:413:in `block in make_lambda'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:600:in `catch'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:600:in `block in default_terminator'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:198:in `block in halting'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:507:in `block in invoke_before'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:507:in `each'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:507:in `invoke_before'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:130:in `run_callbacks'
    /home/yahonda/git/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:41:in `before_setup'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:852:in `before_setup'


 17) Error:
SchemaDumperDefaultsTest#test_schema_dump_with_float_column_infinity_default:
ActiveRecord::StatementInvalid: OCIError: ORA-01843: not a valid month: CREATE TABLE "DUMP_DEFAULTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "STRING_WITH_DEFAULT" VARCHAR2(255) DEFAULT 'Hello!', "DATE_WITH_DEFAULT" DATE DEFAULT '2014-06-05', "DATETIME_WITH_DEFAULT" TIMESTAMP DEFAULT '2014-06-05 07:17:04', "TIME_WITH_DEFAULT" TIMESTAMP DEFAULT '07:17:04', "DECIMAL_WITH_DEFAULT" DECIMAL(20,10) DEFAULT '1234567890.0123456789')
    stmt.c:243:in oci8lib_250.so
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.3/lib/oci8/cursor.rb:129:in `exec'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.3/lib/oci8/oci8.rb:276:in `exec_internal'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.3/lib/oci8/oci8.rb:267:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:429:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:90:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/monitor.rb:214:in `mon_synchronize'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1037:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `execute'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:76:in `create_table'
    /home/yahonda/git/rails/activerecord/test/cases/schema_dumper_test.rb:425:in `block in <class:SchemaDumperDefaultsTest>'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:413:in `instance_exec'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:413:in `block in make_lambda'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:600:in `catch'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:600:in `block in default_terminator'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:198:in `block in halting'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:507:in `block in invoke_before'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:507:in `each'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:507:in `invoke_before'
    /home/yahonda/git/rails/activesupport/lib/active_support/callbacks.rb:130:in `run_callbacks'
    /home/yahonda/git/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:41:in `before_setup'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:852:in `before_setup'


 18) Failure:
TimePrecisionTest#test_schema_dump_includes_time_precision [/home/yahonda/git/rails/activerecord/test/cases/time_precision_test.rb:67]:
Expected /t\.time\s+"start",\s+precision: 4$/ to match "# This file is auto-generated from the current state of the database. Instead\n# of editing this file, please use the migrations feature of Active Record to\n# incrementally modify your database, and then regenerate this schema definition.\n#\n# Note that this schema.rb definition is the authoritative source for your\n# database schema. If you need to create the application database on another\n# system, you should be using db:schema:load, not running all the migrations\n# from scratch. The latter is a flawed and unsustainable approach (the more migrations\n# you'll amass, the slower it'll run and the greater likelihood for issues).\n#\n# It's strongly recommended that you check this file into your version control system.\n\nActiveRecord::Schema.define(version: 0) do\n\n  create_table \"foos\", force: :cascade do |t|\n    t.datetime \"start\", precision: 4\n    t.datetime \"finish\", precision: 6\n  end\n\nend\n".



 42) Failure:
CoreTest#test_pretty_print_persisted [/home/yahonda/git/rails/activerecord/test/cases/core_test.rb:90]:
Expected /\A#<Topic:0x\w+
 id: 1,
 title: "The First Topic",
 author_name: "David",
 author_email_address: "david@loudthinking.com",
 written_on: 2003-07-16 14:28:11 UTC,
 bonus_time: 2000-01-01 14:28:00 UTC,
 last_read: Thu, 15 Apr 2004,
 content: "Have a nice day",
 important: nil,
 approved: false,
 replies_count: 1,
 unique_replies_count: 0,
 parent_id: nil,
 parent_title: nil,
 type: nil,
 group: nil,
 created_at: [^,]+,
 updated_at: [^,>]+>
\z/ to match "#<Topic:0x000056398bf0ab48\n id: 1,\n title: \"The First Topic\",\n author_name: \"David\",\n author_email_address: \"david@loudthinking.com\",\n written_on: 2003-07-16 14:28:11 UTC,\n bonus_time: 2005-01-30 14:28:00 UTC,\n last_read: Thu, 15 Apr 2004,\n content: \"Have a nice day\",\n important: nil,\n approved: false,\n replies_count: 1,\n unique_replies_count: 0,\n parent_id: nil,\n parent_title: nil,\n type: nil,\n group: nil,\n created_at: 2017-04-01 23:45:30 UTC,\n updated_at: 2017-04-01 23:45:30 UTC>\n".



 46) Failure:
AttributeMethodsTest#test_removing_time_zone-aware_types [/home/yahonda/git/rails/activerecord/test/cases/attribute_methods_test.rb:748]:
--- expected
+++ actual
@@ -1 +1 @@
-2000-01-01 10:00:00 UTC
+Sat, 01 Apr 2017 10:00:00 PDT -07:00



 47) Failure:
AttributeMethodsTest#test_setting_a_time_zone-aware_time_in_the_current_time_zone [/home/yahonda/git/rails/activerecord/test/cases/attribute_methods_test.rb:720]:
--- expected
+++ actual
@@ -1 +1 @@
-Sat, 01 Jan 2000 10:00:00 PST -08:00
+Sat, 01 Apr 2017 10:00:00 PDT -07:00
```

### What's next?

* I'd suggest to consider if you really need `Time` type

* Check the "Database Ideas" forum at Oracle Technilogy Network and vote for `TIME` sql data type support (if your answer is yes).

https://community.oracle.com/community/database/database-ideas

* At Oracle enhanced adapter implementation, create another `Time` type or using existing ones and implement our own `quoted_time` to eliminate year, month and day information from timestamp sql type. As of right now I do not have priority for this feature. but pull requests are welcomed.

This issue is rather opened to inform the current status, it will be closed later.

**Comment by yahonda** [comment]
Closing this issue since there is no plan to fix these Time type. If anyone is interested in this topic, please open a pull request to address them.
