### ISSUE TITLE
ActiveRecord::NotNullViolation since rails/rails#29378 

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1357]
Oracle enhanced adapter needs support rails/rails#29378 .

### Steps to reproduce

```ruby
$ cd rails/activerecord
$ git reset --hard 9b8c7796a9c2048208aa843ad3dc477dffa8bdee
$ ARCONN=oracle bin/test test/cases/associations/eager_test.rb:520
```

### Expected behavior
It should finish successfully.

### Actual behavior

```ruby
$ ARCONN=oracle bin/test test/cases/associations/eager_test.rb:520
Using oracle
Run options: --seed 18195

# Running:

E

Error:
EagerAssociationTest#test_eager_with_has_many_through_an_sti_join_model_with_conditions_on_both:
ActiveRecord::NotNullViolation: OCIError: ORA-01400: cannot insert NULL into ("ARUNIT"."SUBSCRIBERS"."ID"): INSERT INTO "SUBSCRIBERS" ("NICK", "NAME") VALUES ('alterself', 'Luke Holden')
    stmt.c:243:in oci8lib_250.so
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.4/lib/oci8/cursor.rb:130:in `exec'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.4/lib/oci8/oci8.rb:277:in `exec_internal'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.4/lib/oci8/oci8.rb:268:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:429:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:90:in `exec'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `block in execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/monitor.rb:214:in `mon_synchronize'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
    /home/yahonda/git/rails/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:989:in `log'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:11:in `execute'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `insert_fixture'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:206:in `insert_fixture'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:571:in `block (5 levels) in create_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:570:in `each'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:570:in `block (4 levels) in create_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:569:in `each'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:569:in `block (3 levels) in create_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:558:in `each'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:558:in `block (2 levels) in create_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:226:in `block in transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
    /home/yahonda/.rbenv/versions/2.5.0-dev/lib/ruby/2.5.0/monitor.rb:214:in `mon_synchronize'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:226:in `transaction'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:556:in `block in create_fixtures'
    /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:418:in `disable_referential_integrity'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:541:in `create_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:1040:in `load_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:977:in `setup_fixtures'
    /home/yahonda/git/rails/activerecord/lib/active_record/fixtures.rb:869:in `before_setup'


bin/test test/cases/associations/eager_test.rb:520



Finished in 2.256818s, 0.4431 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**:master branch

**Oracle enhanced adapter version**:master branch

**Ruby version**:ruby 2.5.0dev (2017-06-12 trunk 59070) [x86_64-linux]

**Oracle Database version**:Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by yahonda** [comment]
Closed since rails/rails#29470 has been merged to master.
