### ISSUE TITLE
error in migration rails 5.1.1 + activerecord-oracle_enhanced-adapter', '~> 1.8.0' + ruby-oci8 + ruby 2.4.1

### ISSUE THREAD

**Issue by williambetancur** [rsim/oracle-enhanced#1369]
```ruby
desarrollo@desarrollo-Inspiron-3458:~/proyectos/rails511/adminlte$ rails db:migrate
rails aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-01006: la variable de enlace no existe: SELECT synonym_name, table_owner, table_name, db_link FROM all_synonyms where owner = SYS_CONTEXT('userenv', 'session_user')
stmt.c:243:in oci8lib_240.so
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/ruby-oci8-2.2.4.1/lib/oci8/cursor.rb:127:in `exec'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:148:in `exec'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:39:in `block in exec_query'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1037:in `log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:22:in `exec_query'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `select'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/schema_statements_ext.rb:52:in `synonyms'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:42:in `synonyms'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:28:in `tables'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/schema_dumper.rb:37:in `dump'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/schema_dumper.rb:21:in `dump'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:241:in `block (4 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:240:in `open'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:240:in `block (3 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:59:in `block (2 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/command.rb:46:in `invoke'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
/home/desarrollo/proyectos/rails511/adminlte/bin/rails:9:in `require'
/home/desarrollo/proyectos/rails511/adminlte/bin/rails:9:in `<top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/desarrollo/proyectos/rails511/adminlte/bin/spring:15:in `require'
/home/desarrollo/proyectos/rails511/adminlte/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
OCIError: ORA-01006: la variable de enlace no existe
stmt.c:243:in oci8lib_240.so
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/ruby-oci8-2.2.4.1/lib/oci8/cursor.rb:127:in `exec'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:148:in `exec'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:39:in `block in exec_query'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1037:in `log'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:22:in `exec_query'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `select'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/schema_statements_ext.rb:52:in `synonyms'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:42:in `synonyms'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-oracle_enhanced-adapter-1.8.1/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:28:in `tables'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/schema_dumper.rb:37:in `dump'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/schema_dumper.rb:21:in `dump'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:241:in `block (4 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:240:in `open'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:240:in `block (3 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:59:in `block (2 levels) in <top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/command.rb:46:in `invoke'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
/home/desarrollo/proyectos/rails511/adminlte/bin/rails:9:in `require'
/home/desarrollo/proyectos/rails511/adminlte/bin/rails:9:in `<top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/desarrollo/.rvm/gems/ruby-2.4.1@try511/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/desarrollo/proyectos/rails511/adminlte/bin/spring:15:in `require'
/home/desarrollo/proyectos/rails511/adminlte/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

**Comment by yahonda** [comment]
Please include the necessary information suggested in https://github.com/rsim/oracle-enhanced/blob/master/.github/issue_template.md 

Thanks.

**Comment by williambetancur** [comment]
Run the gem test and then test the project and work. Thank you very much

**Comment by yahonda** [comment]
Thanks for the update.
