### ISSUE TITLE
 1) bug test should pass association stuff  Failure/Error: post = Post.create! rails 5.03 and oracle

### ISSUE THREAD

**Issue by williambetancur** [rsim/oracle-enhanced#1372]
### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead
```ruby
wifer@wifer-X441UVK:~/alfa/g-intac/oracle-enhanced/guides/bug_report_templates$ rspec active_record_gem_spec.rb 
Fetching git://github.com/rails/rails.git
Fetching git://github.com/rails/arel.git
Fetching git://github.com/rsim/oracle-enhanced.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.4
Using minitest 5.10.2
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubi 1.6.1
Using mini_portile2 2.2.0
Using rack 2.0.3
Using nio4r 2.1.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 8.0.0 from git://github.com/rails/arel.git (at master@67a51c6)
Using bundler 1.15.1
Using method_source 0.8.2
Using thor 0.19.4
Using ruby-plsql 0.6.0
Using rspec-support 3.6.0
Using diff-lcs 1.3
Using ruby-oci8 2.2.4.1
Using tzinfo 1.2.3
Using nokogiri 1.8.0
Using rack-test 0.6.3
Using sprockets 3.7.1
Using websocket-driver 0.6.5
Using mime-types 3.1
Using rspec-core 3.6.0
Using rspec-expectations 3.6.0
Using rspec-mocks 3.6.0
Using activesupport 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using loofah 2.0.3
Using mail 2.6.6
Fetching rspec 3.6.0
Installing rspec 3.6.0
Using rails-dom-testing 2.0.3
Using globalid 0.4.0
Using activemodel 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using rails-html-sanitizer 1.0.3
Using activejob 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using activerecord 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using actionview 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using activerecord-oracle_enhanced-adapter 1.9.0.alpha from git://github.com/rsim/oracle-enhanced.git (at master@d4ecc0f)
Using actionpack 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using actioncable 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using actionmailer 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using railties 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Using sprockets-rails 3.2.0
Using rails 5.2.0.alpha from git://github.com/rails/rails.git (at master@c8ce345)
Warning: NLS_LANG is not set. fallback to US7ASCII.
-- create_table(:posts, {:force=>true})
D, [2017-07-06T06:46:02.991974 #5752] DEBUG -- :    (235.3ms)  DROP TABLE "POSTS"
D, [2017-07-06T06:46:03.189849 #5752] DEBUG -- :    (196.4ms)  DROP SEQUENCE "POSTS_SEQ"
D, [2017-07-06T06:46:03.403415 #5752] DEBUG -- :    (212.4ms)  CREATE TABLE "POSTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY)
D, [2017-07-06T06:46:03.606074 #5752] DEBUG -- :    (202.1ms)  CREATE SEQUENCE "POSTS_SEQ" START WITH 10000
   -> 3.7950s
-- create_table(:comments, {:force=>true})
D, [2017-07-06T06:46:04.001458 #5752] DEBUG -- :    (216.1ms)  DROP TABLE "COMMENTS"
D, [2017-07-06T06:46:04.194799 #5752] DEBUG -- :    (192.6ms)  DROP SEQUENCE "COMMENTS_SEQ"
D, [2017-07-06T06:46:04.403493 #5752] DEBUG -- :    (207.5ms)  CREATE TABLE "COMMENTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "POST_ID" NUMBER(38))
D, [2017-07-06T06:46:04.592083 #5752] DEBUG -- :    (187.8ms)  CREATE SEQUENCE "COMMENTS_SEQ" START WITH 10000
   -> 0.9856s
D, [2017-07-06T06:46:04.822675 #5752] DEBUG -- :    (183.7ms)  SELECT SYS_CONTEXT('userenv', 'current_schema') FROM dual
D, [2017-07-06T06:46:06.277314 #5752] DEBUG -- :    (1079.5ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'TESEO' AND cols.table_name = 'AR_INTERNAL_METADATA' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
D, [2017-07-06T06:46:06.466038 #5752] DEBUG -- :   ActiveRecord::InternalMetadata Load (183.4ms)  SELECT  "AR_INTERNAL_METADATA".* FROM "AR_INTERNAL_METADATA" WHERE "AR_INTERNAL_METADATA"."KEY" = :a1 FETCH FIRST :a2 ROWS ONLY  [["key", "environment"], ["LIMIT", 1]]
D, [2017-07-06T06:46:06.648282 #5752] DEBUG -- :    (181.3ms)  SELECT SYS_CONTEXT('userenv', 'current_schema') FROM dual
D, [2017-07-06T06:46:07.774548 #5752] DEBUG -- :    (560.7ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'TESEO' AND cols.table_name = 'POSTS' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
D, [2017-07-06T06:46:08.432779 #5752] DEBUG -- :    (358.9ms)  SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')
F

Failures:

  1) bug test should pass association stuff
     Failure/Error: post = Post.create!
     
     ActiveRecord::StatementInvalid:
       OCIError: ORA-01006: bind variable does not exist: SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')
     # stmt.c:243:in oci8lib_240.so
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/gems/ruby-oci8-2.2.4.1/lib/oci8/cursor.rb:127:in `exec'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/oracle-enhanced-d4ecc0f42f48/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:148:in `exec'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/oracle-enhanced-d4ecc0f42f48/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:39:in `block in exec_query'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block (2 levels) in log'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/oracle-enhanced-d4ecc0f42f48/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:989:in `log'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/oracle-enhanced-d4ecc0f42f48/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:22:in `exec_query'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:411:in `select'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_rows'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:60:in `select_values'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/oracle-enhanced-d4ecc0f42f48/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:565:in `views'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:36:in `rescue in data_sources'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:34:in `data_sources'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/oracle-enhanced-d4ecc0f42f48/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:530:in `data_sources'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/schema_cache.rb:112:in `prepare_data_sources'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/schema_cache.rb:46:in `data_source_exists?'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/model_schema.rb:318:in `table_exists?'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/attribute_methods.rb:162:in `attribute_names'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/attribute_methods.rb:62:in `block in define_attribute_methods'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/attribute_methods.rb:59:in `define_attribute_methods'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/core.rb:324:in `initialize'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/inheritance.rb:65:in `new'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/inheritance.rb:65:in `new'
     # /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/persistence.rb:50:in `create!'
     # ./active_record_gem_spec.rb:67:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NotImplementedError:
     #   NotImplementedError
     #   /home/wifer/.rvm/gems/ruby-2.4.1@teseo/bundler/gems/rails-c8ce3459648c/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1361:in `data_source_sql'

Finished in 8.63 seconds (files took 8.72 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./active_record_gem_spec.rb:66 # bug test should pass association stuff
```

### System configuration
**Rails version**: 5.0.3 and 5.0.4

**Oracle enhanced adapter version**:
activerecord-oracle_enhanced-adapter (1.7.11)

**Ruby version**:  2.4.1

**Oracle Database version**:
oracle database 12.1.0.2

**Comment by yahonda** [comment]
Thanks for the report.
This error reminds me #1130, which was addressed by applying "DB PSU 12.1.0.2.161018 (Oct2016)" to Oracle database.

```ruby
       OCIError: ORA-01006: bind variable does not exist: SELECT LOWER(view_name) FROM all_views WHERE owner = SYS_CONTEXT('userenv', 'current_schema')
```

Would you take one of these actions and see if you stil see this error:

- Apply "DB PSU 12.1.0.2.161018 (Oct2016)" or newer version of DB PSU, which requires support contact with Oracle
- Upgrade database version to 12.2 

Thanks.
