### ISSUE TITLE
`establish_connection': database configuration specifies nonexistent oracle_enhanced adapter (ActiveRecord::AdapterNotFound)

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#139]
Since https://github.com/rails/rails/commit/dae7b6545372cba40e08554b9a7b2f391eaa5c6e ,

ActiveRecord unit tests for oracle aborted as follows.

``` ruby
$ cd activerecord/
$ rake test_oracle
/home/yahonda/.rvm/rubies/ruby-1.9.3-p0/bin/ruby -w -I"lib:test" -I"/home/yahonda/.rvm/gems/ruby-1.9.3-p0@rails_master/gems/rake-0.9.2.2/lib" "/home/yahonda/.rvm/gems/ruby-1.9.3-p0@rails_master/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb" "test/cases/adapter_test.rb" "test/cases/adapters/oracle/synonym_test.rb" "test/cases/aggregations_test.rb" "test/cases/ar_schema_test.rb" "test/cases/associations/belongs_to_associations_test.rb" "test/cases/associations/callbacks_test.rb" "test/cases/associations/cascaded_eager_loading_test.rb" "test/cases/associations/eager_load_includes_full_sti_class_test.rb" "test/cases/associations/eager_load_nested_include_test.rb" "test/cases/associations/eager_singularization_test.rb" "test/cases/associations/eager_test.rb" "test/cases/associations/extension_test.rb" "test/cases/associations/habtm_join_table_test.rb" "test/cases/associations/has_and_belongs_to_many_associations_test.rb" "test/cases/associations/has_many_associations_test.rb" "test/cases/associations/has_many_through_associations_test.rb" "test/cases/associations/has_one_associations_test.rb" "test/cases/associations/has_one_through_associations_test.rb" "test/cases/associations/identity_map_test.rb" "test/cases/associations/inner_join_association_test.rb" "test/cases/associations/inverse_associations_test.rb" "test/cases/associations/join_model_test.rb" "test/cases/associations/nested_through_associations_test.rb" "test/cases/associations_test.rb" "test/cases/attribute_methods/read_test.rb" "test/cases/attribute_methods_test.rb" "test/cases/autosave_association_test.rb" "test/cases/base_test.rb" "test/cases/batches_test.rb" "test/cases/binary_test.rb" "test/cases/bind_parameter_test.rb" "test/cases/calculations_test.rb" "test/cases/callbacks_test.rb" "test/cases/clone_test.rb" "test/cases/coders/yaml_column_test.rb" "test/cases/column_alias_test.rb" "test/cases/column_definition_test.rb" "test/cases/connection_adapters/abstract_adapter_test.rb" "test/cases/connection_adapters/connection_handler_test.rb" "test/cases/connection_adapters/schema_cache_test.rb" "test/cases/connection_management_test.rb" "test/cases/connection_pool_test.rb" "test/cases/connection_specification/resolver_test.rb" "test/cases/counter_cache_test.rb" "test/cases/custom_locking_test.rb" "test/cases/database_statements_test.rb" "test/cases/date_time_test.rb" "test/cases/defaults_test.rb" "test/cases/deprecated_finder_test.rb" "test/cases/dirty_test.rb" "test/cases/dup_test.rb" "test/cases/dynamic_finder_match_test.rb" "test/cases/explain_test.rb" "test/cases/finder_respond_to_test.rb" "test/cases/finder_test.rb" "test/cases/fixtures/file_test.rb" "test/cases/fixtures_test.rb" "test/cases/habtm_destroy_order_test.rb" "test/cases/i18n_test.rb" "test/cases/identity_map/middleware_test.rb" "test/cases/identity_map_test.rb" "test/cases/inclusion_test.rb" "test/cases/inheritance_test.rb" "test/cases/invalid_date_test.rb" "test/cases/invertible_migration_test.rb" "test/cases/json_serialization_test.rb" "test/cases/lifecycle_test.rb" "test/cases/locking_test.rb" "test/cases/log_subscriber_test.rb" "test/cases/mass_assignment_security_test.rb" "test/cases/method_scoping_test.rb" "test/cases/migration/command_recorder_test.rb" "test/cases/migration_test.rb" "test/cases/mixin_test.rb" "test/cases/modules_test.rb" "test/cases/multiple_db_test.rb" "test/cases/named_scope_test.rb" "test/cases/nested_attributes_test.rb" "test/cases/persistence_test.rb" "test/cases/pooled_connections_test.rb" "test/cases/primary_keys_test.rb" "test/cases/query_cache_test.rb" "test/cases/quoting_test.rb" "test/cases/readonly_test.rb" "test/cases/reflection_test.rb" "test/cases/relation_scoping_test.rb" "test/cases/relation_test.rb" "test/cases/relations_test.rb" "test/cases/reload_models_test.rb" "test/cases/sanitize_test.rb" "test/cases/schema_dumper_test.rb" "test/cases/serialization_test.rb" "test/cases/session_store/session_test.rb" "test/cases/store_test.rb" "test/cases/timestamp_test.rb" "test/cases/transaction_callbacks_test.rb" "test/cases/transactions_test.rb" "test/cases/unconnected_test.rb" "test/cases/validations/association_validation_test.rb" "test/cases/validations/i18n_generate_message_validation_test.rb" "test/cases/validations/i18n_validation_test.rb" "test/cases/validations/uniqueness_validation_test.rb" "test/cases/validations_test.rb" "test/cases/xml_serialization_test.rb" "test/cases/yaml_serialization_test.rb" 
Using oracle with Identity Map off
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:911: warning: assigned but unused variable - owner
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:911: warning: assigned but unused variable - db_link
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:209: warning: assigned but unused variable - e
/home/yahonda/.rvm/gems/ruby-1.9.3-p0@rails_master/gems/ruby-oci8-2.1.0/lib/oci8/object.rb:374: warning: assigned but unused variable - args
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb:71: warning: assigned but unused variable - result
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:52: warning: assigned but unused variable - pk_seq
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:152: warning: assigned but unused variable - pk_seq
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb:152: warning: assigned but unused variable - lines
/home/yahonda/Dropbox/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb:258: warning: assigned but unused variable - e
/home/yahonda/Dropbox/git/rails/activerecord/lib/active_record/connection_handling.rb:44:in `establish_connection': database configuration specifies nonexistent oracle_enhanced adapter (ActiveRecord::AdapterNotFound)
    from /home/yahonda/Dropbox/git/rails/activerecord/test/support/connection.rb:17:in `connect'
    from /home/yahonda/Dropbox/git/rails/activerecord/test/cases/helper.rb:25:in `<top (required)>'
    from /home/yahonda/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/yahonda/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/yahonda/Dropbox/git/rails/activerecord/test/cases/adapter_test.rb:1:in `<top (required)>'
    from /home/yahonda/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/yahonda/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/yahonda/.rvm/gems/ruby-1.9.3-p0@rails_master/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
    from /home/yahonda/.rvm/gems/ruby-1.9.3-p0@rails_master/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `select'
    from /home/yahonda/.rvm/gems/ruby-1.9.3-p0@rails_master/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [/home/yahonda/.rvm/rubies/ruby-1.9.3-p0/bi...]

Tasks: TOP => test_oracle
(See full trace by running task with --trace)
$ 
```

**Comment by Faq** [comment]
Got this when switched to 7.2 rails, same with 8.0
```
ActiveRecord::AdapterNotFound: Database configuration specifies nonexistent 'oracle_enhanced' adapter.
Available adapters are: mysql2, postgresql, sqlite3, trilogy. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile if it's not in the list of available adapters.
(ActiveRecord::AdapterNotFound)
```

When used 3 project setup, where **internal** and **public**, share code from 3rd project made as **core** gem. Pre 7.2, in core:
```
s.add_dependency "activerecord-oracle_enhanced-adapter", "~> 8.0.0"
```
was working fine, but starting from 7.2 and 8.0, need also add in **internal** and **public** Gemfile `gem "activerecord-oracle_enhanced-adapter", "~> 8.0.0"`
