### ISSUE TITLE
 OracleEnhancedAdapter Transaction Raises Deadlocked when a deadlock is encountered fails with Oracle Database 12c

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1599]
### Steps to reproduce
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:575
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:575
==> Loading config from ENV or use default
==> Running specs with MRI version 2.4.2
==> Effective ActiveRecord version 5.2.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[575]}}
F

Failures:

  1) OracleEnhancedAdapter Transaction Raises Deadlocked when a deadlock is encountered
     Failure/Error:
             expect {
               barrier = Concurrent::CyclicBarrier.new(2)

               t1 = TestPost.create(title: "one")
               t2 = TestPost.create(title: "two")

               thread = Thread.new do
                 TestPost.transaction do
                   t1.lock!
                   barrier.wait

       expected ActiveRecord::Deadlocked, got #<ArgumentError:             'Combination of limit and lock is not supported.
                   because gen...erated SQL statements
                   `SELECT FOR UPDATE and FETCH FIRST n ROWS` generates ORA-02014.`
       > with backtrace:
         # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/arel-8f1db57f2d0f/lib/arel/visitors/oracle12.rb:10:in `visit_Arel_Nodes_SelectStatement'
         # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/arel-8f1db57f2d0f/lib/arel/visitors/reduce.rb:15:in `visit'
         # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/arel-8f1db57f2d0f/lib/arel/visitors/reduce.rb:8:in `accept'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/determine_if_preparable_visitor.rb:10:in `accept'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:23:in `to_sql_and_binds'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:48:in `select_all'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
         # /home/yahonda/git/rails/activerecord/lib/active_record/querying.rb:41:in `find_by_sql'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:535:in `block in exec_queries'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:559:in `skip_query_cache_if_necessary'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:523:in `exec_queries'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:398:in `load'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:191:in `records'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:512:in `find_take'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:102:in `take'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:462:in `find_one'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:443:in `find_with_ids'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation/finder_methods.rb:68:in `find'
         # /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:595:in `block in reload'
         # /home/yahonda/git/rails/activerecord/lib/active_record/scoping/default.rb:34:in `block in unscoped'
         # /home/yahonda/git/rails/activerecord/lib/active_record/relation.rb:272:in `scoping'
         # /home/yahonda/git/rails/activerecord/lib/active_record/scoping/default.rb:34:in `unscoped'
         # /home/yahonda/git/rails/activerecord/lib/active_record/persistence.rb:595:in `reload'
         # /home/yahonda/git/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:34:in `reload'
         # /home/yahonda/git/rails/activerecord/lib/active_record/associations.rb:255:in `reload'
         # /home/yahonda/git/rails/activerecord/lib/active_record/autosave_association.rb:231:in `reload'
         # /home/yahonda/git/rails/activerecord/lib/active_record/aggregations.rb:15:in `reload'
         # /home/yahonda/git/rails/activerecord/lib/active_record/locking/pessimistic.rb:73:in `lock!'
         # ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:584:in `block (6 levels) in <top (required)>'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:230:in `block in within_new_transaction'
         # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
         # /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
         # /home/yahonda/git/rails/activerecord/lib/active_record/transactions.rb:212:in `transaction'
         # ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:583:in `block (5 levels) in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-support-3.7.0/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-support-3.7.0/lib/rspec/support.rb:106:in `notify_failure'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:576:in `block (3 levels) in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:254:in `instance_exec'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:254:in `block in run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:466:in `block in run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:604:in `run_around_example_hooks_for'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/hooks.rb:466:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example.rb:251:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:624:in `map'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:624:in `run_examples'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:590:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `block in run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `map'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/example_group.rb:591:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `map'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1896:in `with_suite_hooks'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/reporter.rb:79:in `report'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:87:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.0/exe/rspec:4:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.2/bin/rspec:23:in `load'
     # /home/yahonda/.rbenv/versions/2.4.2/bin/rspec:23:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
     # /home/yahonda/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
     # /home/yahonda/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'

Finished in 1.42 seconds (files took 1.06 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:575 # OracleEnhancedAdapter Transaction Raises Deadlocked when a deadlock is encountered

Coverage report generated for RSpec to /home/yahonda/git/oracle-enhanced/coverage. 979 / 2135 LOC (45.85%) covered.
$
```

### System configuration
**Rails version**:master

**Oracle enhanced adapter version**:master

**Ruby version**:ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

**Oracle Database version**:Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by yahonda** [comment]
It is likely this failure caused by Oracle database 12c restrictions. 
With 11gR2 or lower, these `lock!` method generate these sql statement.


https://github.com/rsim/oracle-enhanced/blob/18fbef9e169caba6f1dc397663cd75038af9f3d5/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb#L584

```sql
  TestPost Load (7.2ms)  SELECT  "TEST_POSTS".* FROM "TEST_POSTS" WHERE "TEST_POSTS"."ID" = :a1 AND ROWNUM <= :a2  FOR UPDATE  [["id", 10001], ["LIMIT", 1]]
```


https://github.com/rsim/oracle-enhanced/blob/18fbef9e169caba6f1dc397663cd75038af9f3d5/spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb#L592

```sql
  TestPost Load (2.1ms)  SELECT  "TEST_POSTS".* FROM "TEST_POSTS" WHERE "TEST_POSTS"."ID" = :a1 AND ROWNUM <= :a2  FOR UPDATE  [["id", 10000], ["LIMIT", 1]]
```

If `t1.lock!` or `t2.lock!` method do not call `first` these errors would be resolved.

**Comment by yahonda** [comment]
cc @koic since #1591 added this test.

**Comment by koic** [comment]
Thanks for opening this issue.
I don't have the environment of Oracle 12c,  so it will take time to build the environment.

If it is higher than Oracle 11, how about `skip` this test?
On the premise that `ORA-00060` does not change in Oracle 11 and 12, Travis CI's result will guarantee that there is no breaking due to version difference.

**Comment by yahonda** [comment]
Thanks for the update. 
For the moment I feel like to let this spec fail with Oracle database 12c. 

I'm going to find why `t1.lock!` calls `.first` and would like to find the way how not to call `first` here.

**Comment by yahonda** [comment]
I did not have enough time yet then skipped this spec #1604 .

**Comment by yahonda** [comment]
Closing this since I do and will not have enough time to address it .#1604 will remind us this issue then it should be fine.
