### ISSUE TITLE
NameError "uninitialized constant ActiveRecord::ConnectionAdapters::AbstractAdapter (NameError)" while loading rails app

### ISSUE THREAD

**Issue by drg0072** [rsim/oracle-enhanced#1730]
I am using the activerecord-oracle_enhanced-adapter-1.6.9 for oracle DB connection. while loading the rails app below error is coming.

```ruby
`uninitialized constant ActiveRecord::ConnectionAdapters::AbstractAdapter (NameError)
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-oracle_enhanced-adapter-1.6.9/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:224:in `<module:ConnectionAdapters>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-oracle_enhanced-adapter-1.6.9/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:161:in `<module:ActiveRecord>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-oracle_enhanced-adapter-1.6.9/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:144:in `<top (required)>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-oracle_enhanced-adapter-1.6.9/lib/activerecord-oracle_enhanced-adapter.rb:12:in `block in <class:OracleEnhancedRailtie>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activesupport-3.0.6/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activesupport-3.0.6/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activesupport-3.0.6/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activesupport-3.0.6/lib/active_support/lazy_load_hooks.rb:42:in `each'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activesupport-3.0.6/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-3.0.6/lib/active_record/base.rb:1903:in `<top (required)>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:2:in `<module:ActiveRecord>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:1:in `<top (required)>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:12:in `require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:12:in `<top (required)>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-sqlserver-adapter-3.0.15/lib/active_record/connection_adapters/sqlserver_adapter.rb:3:in `require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-sqlserver-adapter-3.0.15/lib/active_record/connection_adapters/sqlserver_adapter.rb:3:in `<top (required)>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-sqlserver-adapter-3.0.15/lib/activerecord-sqlserver-adapter.rb:1:in `require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/activerecord-sqlserver-adapter-3.0.15/lib/activerecord-sqlserver-adapter.rb:1:in `<top (required)>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
  /corp/sta/var/www/vhosts/staf2-staging/releases/20180606061306/config/application.rb:15:in `<top (required)>'
  /corp/sta/var/www/vhosts/staf2-staging/releases/20180606061306/config/environment.rb:2:in `require'
  /corp/sta/var/www/vhosts/staf2-staging/releases/20180606061306/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/rack-1.2.5/lib/rack/builder.rb:46:in `instance_eval'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/rack-1.2.5/lib/rack/builder.rb:46:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/passenger-4.0.29/helper-scripts/rack-preloader.rb:108:in `eval'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/passenger-4.0.29/helper-scripts/rack-preloader.rb:108:in `preload_app'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/passenger-4.0.29/helper-scripts/rack-preloader.rb:153:in `<module:App>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/passenger-4.0.29/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /corp/sta/opt/rvm/gems/ruby-1.9.3-p429@staf2/gems/passenger-4.0.29/helper-scripts/rack-preloader.rb:28:in `<main>'
`
```

I have checked some post and it advised to insert the oracle.db file in initializers which I already added but still getting this error.

**Rails version**:
rails 3.0.6

**Oracle enhanced adapter version**:
1.6.9

**Ruby version**:
ruby-1.9.3-p429

**Oracle Database version**:
ruby-oci8 (2.2.5.1)

Gemfile.lock 
```ruby
GEM
  remote: http://rubygems.org/
  specs:
    ZenTest (4.6.2)
    abstract (1.0.0)
    actionmailer (3.0.6)
      actionpack (= 3.0.6)
      mail (~> 2.2.15)
    actionpack (3.0.6)
      activemodel (= 3.0.6)
      activesupport (= 3.0.6)
      builder (~> 2.1.2)
      erubis (~> 2.6.6)
      i18n (~> 0.5.0)
      rack (~> 1.2.1)
      rack-mount (~> 0.6.14)
      rack-test (~> 0.5.7)
      tzinfo (~> 0.3.23)
    activemodel (3.0.6)
      activesupport (= 3.0.6)
      builder (~> 2.1.2)
      i18n (~> 0.5.0)
    activerecord (3.0.6)
      activemodel (= 3.0.6)
      activesupport (= 3.0.6)
      arel (~> 2.0.2)
      tzinfo (~> 0.3.23)
    activerecord-oracle_enhanced-adapter (1.6.9)
    activerecord-sqlserver-adapter (3.0.15)
      activerecord (~> 3.0.3)
      arel (~> 2.0.7)
    activeresource (3.0.6)
      activemodel (= 3.0.6)
      activesupport (= 3.0.6)
    activesupport (3.0.6)
    acts_as_tree_rails3 (0.1.0)
    arel (2.0.10)
    autotest (4.4.6)
      ZenTest (>= 4.4.1)
    awesome_print (1.2.0)
    axlsx (2.0.1)
      htmlentities (~> 4.3.1)
      nokogiri (>= 1.4.1)
      rubyzip (~> 1.0.0)
    bcrypt-ruby (3.0.1)
    builder (2.1.2)
    capistrano (2.12.0)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capybara (1.1.2)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      selenium-webdriver (~> 2.0)
      xpath (~> 0.1.4)
    chartkick (2.2.4)
    childprocess (0.3.0)
      ffi (~> 1.0.6)
    chronic (0.9.1)
    columnize (0.8.9)
    cucumber (1.1.4)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.2)
      gherkin (~> 2.7.1)
      json (>= 1.4.6)
      term-ansicolor (>= 1.0.6)
    cucumber-rails (1.2.1)
      capybara (>= 1.1.2)
      cucumber (>= 1.1.3)
      nokogiri (>= 1.5.0)
    debugger (1.6.8)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.2.0)
      debugger-ruby_core_source (~> 1.3.5)
    debugger-linecache (1.2.0)
    debugger-ruby_core_source (1.3.5)
    debugger-xml (0.3.3)
      builder (>= 2.0.0)
      debugger (>= 1.6.2)
    devise (1.5.3)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.0.3)
      warden (~> 1.1)
    devise_ldap_authenticatable (0.5.1)
      devise (~> 1.5.0)
      net-ldap (~> 0.2.2)
    diff-lcs (1.1.3)
    erubis (2.6.6)
      abstract (>= 1.0.0)
    ffi (1.0.11)
    gherkin (2.7.6)
      json (>= 1.4.6)
    gruff (0.3.6)
    haml (3.1.4)
    haml-rails (0.3.4)
      actionpack (~> 3.0)
      activesupport (~> 3.0)
      haml (~> 3.0)
      railties (~> 3.0)
    highline (1.6.13)
    hoe (3.0.6)
      rake (~> 0.8)
    htmlentities (4.3.4)
    i18n (0.5.4)
    jira-ruby (0.1.8)
      activesupport
      oauth
    jquery-rails (1.0.19)
      railties (~> 3.0)
      thor (~> 0.14)
    json (1.6.5)
    mail (2.2.19)
      activesupport (>= 2.3.6)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.17.2)
    multi_json (1.0.4)
    mysql (2.9.1)
    mysql2 (0.2.20)
    net-ldap (0.2.2)
    net-scp (1.0.4)
      net-ssh (>= 1.99.1)
    net-sftp (2.0.5)
      net-ssh (>= 2.0.9)
    net-ssh (2.5.2)
    net-ssh-gateway (1.1.0)
      net-ssh (>= 1.99.1)
    nokogiri (1.5.0)
    oauth (0.4.7)
    orm_adapter (0.0.6)
    polyglot (0.3.3)
    rack (1.2.5)
    rack-mount (0.6.14)
      rack (>= 1.0.0)
    rack-test (0.5.7)
      rack (>= 1.0)
    rails (3.0.6)
      actionmailer (= 3.0.6)
      actionpack (= 3.0.6)
      activerecord (= 3.0.6)
      activeresource (= 3.0.6)
      activesupport (= 3.0.6)
      bundler (~> 1.0)
      railties (= 3.0.6)
    railties (3.0.6)
      actionpack (= 3.0.6)
      activesupport (= 3.0.6)
      rake (>= 0.8.7)
      thor (~> 0.14.4)
    rake (0.9.2.2)
    rmagick (2.16.0)
    rspec (2.8.0)
      rspec-core (~> 2.8.0)
      rspec-expectations (~> 2.8.0)
      rspec-mocks (~> 2.8.0)
    rspec-core (2.8.0)
    rspec-expectations (2.8.0)
      diff-lcs (~> 1.1.2)
    rspec-mocks (2.8.0)
    rspec-rails (2.8.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec (~> 2.8.0)
    ruby-graphviz (1.0.8)
    ruby-oci8 (2.2.5.1)
    ruby-prof (0.15.2)
    rubyzip (1.0.0)
    rvm-capistrano (1.2.5)
      capistrano (>= 2.0.0)
    sass (3.1.12)
    selenium-webdriver (2.18.0)
      childprocess (>= 0.2.5)
      ffi (~> 1.0.9)
      multi_json (~> 1.0.4)
      rubyzip
    term-ansicolor (1.0.7)
    test-unit (1.2.3)
      hoe (>= 1.5.1)
    thor (0.14.6)
    tiny_tds (0.6.1)
    treetop (1.4.10)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.54)
    warden (1.1.0)
      rack (>= 1.0)
    webrat (0.7.3)
      nokogiri (>= 1.2.0)
      rack (>= 1.0)
      rack-test (>= 0.5.3)
    whenever (0.8.4)
      activesupport (>= 2.3.4)
      chronic (>= 0.6.3)
    will_paginate (3.0.3)
    xpath (0.1.4)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord (~> 3.0.6)
  activerecord-oracle_enhanced-adapter
  activerecord-sqlserver-adapter (= 3.0.15)
  acts_as_tree_rails3
  arel (~> 2.0.7)
  autotest
  awesome_print
  axlsx
  chartkick
  cucumber-rails (>= 0.3.2)
  debugger
  debugger-xml
  devise (>= 1.5.3)
  devise_ldap_authenticatable (>= 0.5.1)
  gruff
  haml (>= 3.0.18)
  haml-rails
  hoe
  jira-ruby (= 0.1.8)
  jquery-rails
  mysql
  mysql2 (= 0.2.20)
  rails (= 3.0.6)
  rake
  rmagick (~> 2.16.0)
 

 rspec-rails (>= 2.0.0.beta.20)
  ruby-graphviz
  ruby-oci8 (~> 2.2.5.1)
  ruby-prof
  rubyzip (= 1.0.0)
  rvm-capistrano
  sass
  test-unit (~> 1.2)
  tiny_tds
  webrat (>= 0.7.2.beta.1)
  whenever
  will_paginate (~> 3.0)
```

Attaching file with complete details of ENV and LOAD_PATH
[uninitialized constant ActiveRecord.pdf](https://github.com/rsim/oracle-enhanced/files/2126613/uninitialized.constant.ActiveRecord.pdf)

**Comment by yahonda** [comment]
Hi,

Oracle enhanced adapter 1.6.9 only supports Rails 4.2. You will need to use Oracle enhanced adapter 1.4 with Rails 3 or upgrade Rails version to 4.2 with Oracle enhanced adapter 1.6.9.
