### ISSUE TITLE
"No shared library is found to hook." on oci8 2.2.6 but not 2.2.5.1 on MacOS - IC 12.1.0.2.

### ISSUE THREAD

**Issue by Adam21e** [rsim/oracle-enhanced#1768]
### Steps to reproduce
Hi,
On a Mac I upgraded to Rails 5.2 and oracle-enhanced 5.2 and now get "No shared library is found to hook." 
This fails with oci8 2.2.6 but not 2.2.5.1
I am connecting to Oracle Express running in a linux VM. Oci8 2.2.6 works if I connect directly.

Not sure what to do from here.

### Expected behavior
Should create table etc in test

### Actual behavior
I ran the testcase and got this:
```
ruby active_record_gem.rb
Fetching https://github.com/rails/rails.git
Fetching https://github.com/rsim/oracle-enhanced.git
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies....
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 1.1.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using builder 3.2.3
Using erubi 1.7.1
Using mini_portile2 2.3.0
Using nokogiri 1.8.4
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.2
Using rails-html-sanitizer 1.0.4
Using actionview 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using rack 2.0.5
Using rack-test 1.1.0
Using actionpack 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using actioncable 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using globalid 0.4.1
Using activejob 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using mini_mime 1.0.1
Using mail 2.7.0
Using actionmailer 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using activemodel 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using activerecord 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using ruby-plsql 0.7.1
Using activerecord-oracle_enhanced-adapter 6.0.0.alpha from https://github.com/rsim/oracle-enhanced.git (at master@f14997e)
Using mimemagic 0.3.2
Using marcel 0.3.2
Using activestorage 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using bundler 1.16.2
Using byebug 10.0.2
Using method_source 0.9.0
Using thor 0.20.0
Using railties 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 6.0.0.alpha from https://github.com/rails/rails.git (at master@a8359d8)
Using ruby-oci8 2.2.6
-- create_table(:posts, {:force=>true})
Traceback (most recent call last):
	28: from active_record_gem.rb:56:in `<main>'
	27: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/schema.rb:46:in `define'
	26: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/schema.rb:50:in `define'
	25: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/schema.rb:50:in `instance_eval'
	24: from active_record_gem.rb:57:in `block in <main>'
	23: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/migration.rb:866:in `method_missing'
	22: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/migration.rb:845:in `say_with_time'
	21: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
	20: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/migration.rb:845:in `block in say_with_time'
	19: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/migration.rb:867:in `block in method_missing'
	18: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/migration.rb:860:in `connection'
	17: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_handling.rb:67:in `connection'
	16: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_handling.rb:95:in `retrieve_connection'
	15: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
	14: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
	13: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
	12: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
	11: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
	10: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
	 9: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/rails-a8359d837cc0/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
	 8: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:73:in `oracle_enhanced_connection'
	 7: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:11:in `create'
	 6: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:11:in `new'
	 5: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:31:in `initialize'
	 4: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:31:in `new'
	 3: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:364:in `initialize'
	 2: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/oracle-enhanced-f14997eaedb6/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:309:in `new_connection'
	 1: from /Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.6/lib/oci8/properties.rb:74:in `[]='
/Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.6/lib/oci8/properties.rb:74:in `__set_prop': No shared library is found to hook. (RuntimeError)
```

If I run the ruby-oci8 style example (updated for my system) on the command line it connects to the database fine.
`ruby -r oci8 -e "OCI8.new('scott', 'tiger').exec('select * from emp') do |r| puts r.join(','); end`

### System configuration
**Rails version**:
5.2.0 (and above)
**Oracle enhanced adapter version**:
5.2.0 - 5.2.2
**Ruby version**:
2.3.4 and 2.5.1
**oci8**
2.2.6
**Oracle Database version**:
11g Express edition 11.2.0.2.0 64bit running in a linux VM
**OS** 
OS X 10.12.6 
**InstantClient version**
12.1.0.2.

**Comment by yahonda** [comment]
Hi, 

"No shared library is found to hook." reminds me https://github.com/rsim/oracle-enhanced/issues/1754 , which addresses the "No shared library is found to hook." with Oracle 18c client.

```ruby
/Users/adam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ruby-oci8-2.2.6/lib/oci8/properties.rb:74:in `__set_prop': No shared library is found to hook. (RuntimeError)
```

Would you report this to https://github.com/kubo/ruby-oci8/issues ?

cc @kubo

**Comment by kubo** [comment]
@Adam21e Sorry, it is a bug in ruby-oci8 2.2.6. I'll release 2.2.6.1, which fixes this issue only, in a few days.

If you need fixed version soon, run the following commands.
```shell
$ curl -LO https://dl.bintray.com/kubo/generic/ruby-oci8-2.2.6.tar.gz
$ tar xvfz ruby-oci8-2.2.6.tar.gz 
$ cd ruby-oci8-2.2.6
$ sed -i -e 's/libclntsh\.so/libclntsh.dylib/' ext/oci8/hook_funcs.c  # replaces libclntsh.so with libclntsh.dylib in ext/oci8/hook_funcs.c
$ gem build ruby-oci8.gemspec # creates a new gem, which is available only on macOS.
$ gem install ./ruby-oci8-2.2.6.gem 
```

**Comment by yahonda** [comment]
Thanks for the fix.

**Comment by Adam21e** [comment]
@yahonda Sorry for the late reply. Thanks for cc'ing @kudo

Thanks @kubo for the fast update, wow that was fast. 🥇 :-)

**Comment by kubo** [comment]
ruby-oci8 2.2.6.1 was released.
