### ISSUE TITLE
ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'oracle_enhanced' adapter

### ISSUE THREAD

**Issue by cmason** [rsim/oracle-enhanced#1769]
### Steps to reproduce

Run `$ rails db:structure:dump --trace`

### Expected behavior

Dump the database structure to db/structure.sql

### Actual behavior

```
$ rails db:structure:dump --trace
** Invoke db:structure:dump (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
Logging at level: 0
** Execute db:load_config
** Execute db:structure:dump
rails aborted!
ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'oracle_enhanced' adapter
/Users/cmason/.gem/ruby/2.5.1/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:304:in `class_for_adapter'
/Users/cmason/.gem/ruby/2.5.1/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:228:in `structure_dump'
/Users/cmason/.gem/ruby/2.5.1/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:287:in `block (3 levels) in <main>'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/cmason/.rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/cmason/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/cmason/.gem/ruby/2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/cmason/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/cmason/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/Users/cmason/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/Users/cmason/.gem/ruby/2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/cmason/.gem/ruby/2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/cmason/.gem/ruby/2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/cmason/.gem/ruby/2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/cmason/.gem/ruby/2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/cmason/.gem/ruby/2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/cmason/.gem/ruby/2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/cmason/.gem/ruby/2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
bin/rails:6:in `<main>'
Tasks: TOP => db:structure:dump
```

### System configuration
**Rails version**: 5.2.0

**Oracle enhanced adapter version**:  5.2.3

**Ruby version**: 2.5.1p57

**Oracle Database version**:  oracle-xe-11g

**Gemfile**:

```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '5.2.0'

ruby '~> 2.5.0'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

group :oracle do
  gem 'activerecord-oracle_enhanced-adapter', '~> 5.2.0'
  gem 'ruby-oci8'
end
gem 'pg', '~> 0.18', group: :postgres
```

**Comment by cmason** [comment]
This is because the `oracle` group needs to be explicitly required now with bundler.
