### ISSUE TITLE
two specs fails with jruby-head 

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#1833]
### Steps to reproduce
https://travis-ci.org/rsim/oracle-enhanced/jobs/499529628

```ruby
rspec ./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:276 # OracleEnhancedConnection should fall back to directly instantiating OracleDriver
rspec ./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:198 # OracleEnhancedConnection with host="connection-string" uses the database param as the connection string
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
Failures:
  1) OracleEnhancedConnection should fall back to directly instantiating OracleDriver
     Failure/Error: @raw_connection = java.sql.DriverManager.getConnection(url, properties)
     
       #<Java::JavaSql::DriverManager (class)> received :getConnection with unexpected arguments
         expected: (*(any args))
              got: ("jdbc:oracle:thin:@//127.0.0.1:1521/XE", {"password"=>"oracle_enhanced", "defaultRowPrefetch"=>"100", "user"=>"oracle_enhanced"})
       Diff:
       @@ -1,2 +1,3 @@
       -["*(any args)"]
       +["jdbc:oracle:thin:@//127.0.0.1:1521/XE",
       + {"password"=>"oracle_enhanced", "defaultRowPrefetch"=>"100", "user"=>"oracle_enhanced"}]
       
        Please stub a default value first if message might be received with other args as well. 
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in Support'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:327:in `notify'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:311:in `__raise'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:60:in `raise_missing_default_stub_error'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/proxy.rb:207:in `raise_missing_default_stub_error'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/proxy.rb:192:in `message_received'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/proxy.rb:327:in `message_received'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/method_double.rb:64:in `block in getConnection'
     # ./lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:136:in `new_connection'
     # ./lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:65:in `initialize'
     # ./lib/active_record/connection_adapters/oracle_enhanced/connection.rb:13:in `create'
     # ./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:282:in `block in <main>'
     # org/jruby/RubyBasicObject.java:2681:in `instance_exec'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # org/jruby/RubyArray.java:2577:in `map'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # org/jruby/RubyArray.java:2577:in `map'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'
  2) OracleEnhancedConnection with host="connection-string" uses the database param as the connection string
     Failure/Error: @raw_connection = java.sql.DriverManager.getConnection(url, properties)
     
       #<Java::JavaSql::DriverManager (class)> received :getConnection with unexpected arguments
         expected: ("jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)))", anything)
              got: ("jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)))", {"password"=>"oracle_enhanced", "defaultRowPrefetch"=>"100", "user"=>"oracle_enhanced"})
       Diff:
       @@ -1,3 +1,3 @@
        ["jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XE)))",
       - "anything"]
       + {"password"=>"oracle_enhanced", "defaultRowPrefetch"=>"100", "user"=>"oracle_enhanced"}]
       
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-support-3.8.0/lib/rspec/support.rb:97:in `block in Support'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-support-3.8.0/lib/rspec/support.rb:106:in `notify_failure'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:327:in `notify'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:311:in `__raise'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/error_generator.rb:55:in `raise_unexpected_message_args_error'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/message_expectation.rb:501:in `raise_unexpected_message_args_error'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/proxy.rb:188:in `message_received'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/proxy.rb:327:in `message_received'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-mocks-3.8.0/lib/rspec/mocks/method_double.rb:64:in `block in getConnection'
     # ./lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:136:in `new_connection'
     # ./lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:65:in `initialize'
     # ./lib/active_record/connection_adapters/oracle_enhanced/connection.rb:13:in `create'
     # ./spec/active_record/connection_adapters/oracle_enhanced/connection_spec.rb:204:in `block in <main>'
     # org/jruby/RubyBasicObject.java:2681:in `instance_exec'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
     # org/jruby/RubyArray.java:2577:in `map'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
     # org/jruby/RubyArray.java:2577:in `map'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # org/jruby/RubyArray.java:2577:in `map'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/travis/.rvm/gems/jruby-head/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'
Finished in 1 minute 29.38 seconds (files took 2.46 seconds to load)
370 examples, 2 failures, 6 pending
```

### System configuration
**Rails version**: master branch

**Oracle enhanced adapter version**: master branch

**Ruby version**:jruby 9.2.7.0-SNAPSHOT (2.5.3) 2019-02-27 a09a866 OpenJDK 64-Bit Server VM 11.0.1+13 on 11.0.1+13 [linux-x86_64]

**Oracle Database version**: Oracle Database 11g XE

**Comment by yahonda** [comment]
The last successful build is https://travis-ci.org/rsim/oracle-enhanced/jobs/498977842

**Comment by yahonda** [comment]
Compared JRuby twp commit hash https://github.com/jruby/jruby/compare/e5cb0ac...a09a866 we may need to bisect which commit introduces this behavior.

**Comment by yahonda** [comment]
This issue does not reproduce anymore. https://travis-ci.org/rsim/oracle-enhanced/jobs/518161336
