### ISSUE TITLE
unmofidied version of guides/bug_report_templates/active_record_gem.rb fails with NameError

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#1935]
### Steps to reproduce
in c0ff3a36c025a79c7435c7f9b6a0a2a5fcc6d35c
ruby guides/bug_report_templates/active_record_gem.rb

### Expected behavior
template test to pass

### Actual behavior
```
Traceback (most recent call last):
	5: from guides/bug_report_templates/active_record_gem.rb:22:in `<main>'
	4: from /home/jlahtinen/.rvm/gems/ruby-2.6.3/bundler/gems/oracle-enhanced-c0ff3a36c025/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:33:in `<top (required)>'
	3: from /home/jlahtinen/.rvm/gems/ruby-2.6.3/bundler/gems/rails-923439777ad0/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:15:in `<top (required)>'
	2: from /home/jlahtinen/.rvm/gems/ruby-2.6.3/bundler/gems/rails-923439777ad0/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:16:in `<module:ActiveRecord>'
	1: from /home/jlahtinen/.rvm/gems/ruby-2.6.3/bundler/gems/rails-923439777ad0/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:30:in `<module:ConnectionAdapters>'
/home/jlahtinen/.rvm/gems/ruby-2.6.3/bundler/gems/rails-923439777ad0/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:35:in `<class:AbstractAdapter>': uninitialized constant ActiveRecord::ConnectionAdapters::AbstractAdapter::Quoting (NameError)
```

### System configuration

see commit

**Ruby version**: 2.6

**Comment by yahonda** [comment]
Thanks for the report. Opened a pull request #1936 to run bug templates at CI and it actually reproduces the error reported.
