### ISSUE TITLE
StatementInvalid: OCIError: ORA-00922: missing or invalid option creating activestorage tables

### ISSUE THREAD

**Issue by coreypmurphy** [rsim/oracle-enhanced#1940]
### Steps to reproduce
1) rails new my_app
2) add oracle-enhanced & ruby-oci8 to gemfile
3) bundle
4) configure database.yml
5) rails active_storage:install
6) rake db:schema:load

### Expected behavior
Migration should create table 2 tables

### Actual behavior
Migration fails to create 2 tables

### System configuration
Rails version: 6.0.0
Ruby version: 2.6.3
Oracle enhanced adapter version: 6.0.0
ruby-oci8 version: 2.2.7
Oracle Database version:

### Schema File
```
ActiveRecord::Schema.define(version: 2019_09_13_052449) do

  create_table "active_storage_attachments", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.bigint "record_id", null: false
    t.bigint "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end

  create_table "active_storage_blobs", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.bigint "byte_size", null: false
    t.string "checksum", null: false
    t.datetime "created_at", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end
end
```

### Error Stack Trace
```
-- create_table("active_storage_attachments", {:options=>"ENGINE=InnoDB DEFAULT CHARSET=utf8", :force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-00922: missing or invalid option
stmt.c:267:in oci8lib_260.bundle
/Users/a028541/Documents/apps/regionsedge_library/db/schema.rb:3:in `block in <main>'
/Users/a028541/Documents/apps/regionsedge_library/db/schema.rb:1:in `<main>'

Caused by:
OCIError: ORA-00922: missing or invalid option
stmt.c:267:in oci8lib_260.bundle
/Users/a028541/Documents/apps/regionsedge_library/db/schema.rb:3:in `block in <main>'
/Users/a028541/Documents/apps/regionsedge_library/db/schema.rb:1:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by coreypmurphy** [comment]
Commenting out the schema file line by line seems to indicate the "options" hash in the "create_table" statement is the problem yet I don't recall this being an issue in our other projects that leverage Oracle.  One item of note is our "development" database is mysql and our production is "oracle".

**Comment by coreypmurphy** [comment]
Just removed the "options" param from the create_table statement resolved this error.
