### ISSUE TITLE
Table not found during migration because db session user is empty in describe() method

### ISSUE THREAD

**Issue by coreypmurphy** [rsim/oracle-enhanced#1941]
### Steps to reproduce
1. rails new app with oracle-enhanced and ruby-oci8 gems
2. database.yml configured with just "adapter" and "database" attributes.  Username and password are managed by "tnsname.ora" and wallet files.
NOTE: database is existing and empty (not created by this application)
3. rails g scaffold User name:string
4. rake db:migrate

### Expected behavior
Migration should create users table

### Actual behavior
Adapter connects to database and creates "SCHEMA_MIGRATIONS" and "AR_INTERNAL_METADATA" tables but migration does not complete, and errors with: ```ActiveRecord::ConnectionAdapters::OracleEnhanced::ConnectionException: "DESC schema_migrations" failed; does it exist?```

### System configuration
**Rails version**: 6.0.0
**Oracle enhanced adapter version**: 6.0.0
**Ruby version**: 2.6.3
**Oracle Database version**: 11g

Examining the stack trace (below) and digging into ```connection.rb``` I'm finding that the ```@owner``` variable is empty which causes the ```_select_one(sql)``` method to not return the "schema_migrations" table in the result set.  Taking the same SQL generated (below) by the "describe" method and running it in SQL Developer against the database in question yields the same result.  In SQL Developer, replacing the empty quotes in the ```WHERE owner = ''``` with ```WHERE owner = user```  returns the table record in question because the "user" sql function is pulling in the session user.  Further inspection of the ```describe(name)``` method showed ```@owner``` to be empty during migrations.

### SQL Generated by describe method (connection.rb: line 38):
```
SELECT owner, table_name, 'TABLE' name_type FROM all_tables WHERE owner = '' AND table_name = 'SCHEMA_MIGRATIONS' UNION ALL SELECT owner, view_name table_name, 'VIEW' name_type FROM all_views WHERE owner = '' AND view_name = 'SCHEMA_MIGRATIONS' UNION ALL SELECT table_owner, table_name, 'SYNONYM' name_type FROM all_synonyms WHERE owner = '' AND synonym_name = 'SCHEMA_MIGRATIONS' UNION ALL SELECT table_owner, table_name, 'SYNONYM' name_type FROM all_synonyms WHERE owner = 'PUBLIC' AND synonym_name = 'SCHEMA_MIGRATIONS'
```

### MIGRATION
```
class CreateUsers < ActiveRecord::Migration[6.0]
  def change
    create_table :users do |t|
      t.string :name
      t.timestamps
    end
  end
end
```

### STACK TRACE
```
ActiveRecord::ConnectionAdapters::OracleEnhanced::ConnectionException: "DESC schema_migrations" failed; does it exist?
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-oracle_enhanced-adapter-6.0.0/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:66:in `describe'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-oracle_enhanced-adapter-6.0.0/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:225:in `describe'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-oracle_enhanced-adapter-6.0.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:535:in `column_definitions'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-oracle_enhanced-adapter-6.0.0/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:165:in `columns'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:487:in `load_schema!'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/attributes.rb:247:in `load_schema!'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:480:in `block in load_schema'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:477:in `load_schema'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:352:in `columns_hash'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/inheritance.rb:82:in `descends_from_active_record?'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/inheritance.rb:88:in `finder_needs_type_condition?'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/core.rb:298:in `relation'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/scoping/named.rb:56:in `default_scoped'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/scoping/named.rb:44:in `all'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/querying.rb:21:in `order'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/schema_migration.rb:52:in `all_versions'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1084:in `get_all_versions'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:1083:in `assume_migrated_upto_version'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:54:in `define'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:46:in `define'
/Users/a028541/Documents/apps/regionsedge_library/db/schema.rb:1:in `<main>'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:328:in `load_schema'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `each'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:397:in `block (3 levels) in <main>'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/a028541/.rbenv/versions/2.6.3/bin/rake:23:in `load'
/Users/a028541/.rbenv/versions/2.6.3/bin/rake:23:in `<main>'
```

Additional testing seems to indicate the problem appeared >5.2.0 but is not an issue <=5.2.0.

**Comment by coreypmurphy** [comment]
Successful Test Case:
### Rails version: 5.0.2
### Oracle enhanced adapter version: 1.7.11
### Ruby version: 2.3.4
### Oracle Database version: 11g

Different application connecting to different schema on same database server runs migrations without issue.  This tells me my tnsnames and wallet files are still functioning as desired, with the primary deltas being the version of rails, ruby and the adapter.

**Comment by coreypmurphy** [comment]
Successful Test Case:
### System configuration
**Rails version**: 5.2.0
**Oracle enhanced adapter version**: 5.2.0
**Ruby version**: 2.4.0
**Oracle Database version**: 11g

New application connecting to same schema on same database server runs migrations without issue.

**Comment by coreypmurphy** [comment]
Final Test Case:
### System configuration
**Rails version**: 6.0.0
**Oracle enhanced adapter version**: 6.0.0
**Ruby version**: 2.6.3
**Oracle Database version**: 11g

New application connecting to same (as original post) schema on same database same issue as original post.  Migration fails:

```
ActiveRecord::ConnectionAdapters::OracleEnhanced::ConnectionException: "DESC schema_migrations" failed; does it exist?
/Users/a028541/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-oracle_enhanced-adapter-6.0.0/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:67:in `describe'
```

**Comment by bercob** [comment]
However this issue is automatically closed, but isn't solved. I'm facing with the same problem actually...
