### ISSUE TITLE
ORA-1805 when Oracle Instant Client is 19.6 and Oracle Database is 18.4

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#2033]
### Steps to reproduce

1. Download and install Oracle Instant Client
https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-basic-19.6.0.0.0-1.x86_64.rpm
https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-sqlplus-19.6.0.0.0-1.x86_64.rpm
https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-devel-19.6.0.0.0-1.x86_64.rpm

2. Download and install Oracle Database Express Edition (XE) Release 18.4.0.0.0 (18c) using Docker
https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/18.4.0

3. Install Ruby 2.7.1 

4. Run this spec file
$ bundle exec rspec ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb

### Expected behavior
All of unit tests should pass.

### Actual behavior

It fails with `ORA-01805: possible error in date/time operation` error.

```ruby
$ bundle exec rspec ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb
==> Loading config from ENV or use default
==> Running specs with MRI version 2.7.1
==> Effective ActiveRecord version 6.1.0.alpha
FF

Failures:

  1) OracleEnhancedAdapter timestamp with timezone support / TIMESTAMP WITH TIME ZONE values from ActiveRecord model should return Time value from TIMESTAMP columns
     Failure/Error: if row = @raw_cursor.fetch
     
     ActiveRecord::StatementInvalid:
       OCIError: ORA-01805: possible error in date/time operation
     # ocidatetime.c:119:in oci8lib_270.so
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/datetime.rb:393:in `get'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:576:in `get_data'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:576:in `block in fetch_one_row_as_array'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:575:in `collect'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:575:in `fetch_one_row_as_array'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:162:in `fetch'
     # ./lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:158:in `fetch'
     # ./lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:53:in `block in exec_query'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:690:in `block (2 levels) in log'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:689:in `block in log'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:681:in `log'
     # ./lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb:35:in `log'
     # ./lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:24:in `exec_query'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select_prepared'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:67:in `select_all'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:47:in `find_by_sql'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:848:in `block in exec_queries'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:866:in `skip_query_cache_if_necessary'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:833:in `exec_queries'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:638:in `load'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:249:in `records'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation/finder_methods.rb:508:in `find_take'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation/finder_methods.rb:98:in `take'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation/finder_methods.rb:81:in `find_by'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:226:in `find_or_initialize_by'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:22:in `find_or_initialize_by'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/internal_metadata.rb:33:in `[]='
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/schema.rb:58:in `define'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/schema.rb:46:in `define'
     # ./spec/spec_helper.rb:112:in `schema_define'
     # ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb:10:in `block (2 levels) in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:360:in `instance_exec'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:360:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:524:in `block in run_owned_hooks_for'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:523:in `each'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:523:in `run_owned_hooks_for'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:475:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:553:in `block in run_before_context_hooks'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:552:in `run_before_context_hooks'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:605:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/exe/rspec:4:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/rspec:23:in `load'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/rspec:23:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
     # ------------------
     # --- Caused by: ---
     # OCIError:
     #   ORA-01805: possible error in date/time operation
     #   ocidatetime.c:119:in oci8lib_270.so

  2) OracleEnhancedAdapter timestamp with timezone support / TIMESTAMP WITH TIME ZONE values from ActiveRecord model should return Time value with fractional seconds from TIMESTAMP columns
     Failure/Error: if row = @raw_cursor.fetch
     
     ActiveRecord::StatementInvalid:
       OCIError: ORA-01805: possible error in date/time operation
     # ocidatetime.c:119:in oci8lib_270.so
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/datetime.rb:393:in `get'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:576:in `get_data'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:576:in `block in fetch_one_row_as_array'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:575:in `collect'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:575:in `fetch_one_row_as_array'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/ruby-oci8-55808c1cb4b7/lib/oci8/cursor.rb:162:in `fetch'
     # ./lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:158:in `fetch'
     # ./lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:53:in `block in exec_query'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:690:in `block (2 levels) in log'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:689:in `block in log'
     # /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:681:in `log'
     # ./lib/active_record/connection_adapters/oracle_enhanced/dbms_output.rb:35:in `log'
     # ./lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:24:in `exec_query'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select_prepared'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:67:in `select_all'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:47:in `find_by_sql'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:848:in `block in exec_queries'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:866:in `skip_query_cache_if_necessary'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:833:in `exec_queries'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:638:in `load'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:249:in `records'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation/finder_methods.rb:508:in `find_take'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation/finder_methods.rb:98:in `take'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation/finder_methods.rb:81:in `find_by'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:226:in `find_or_initialize_by'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/querying.rb:22:in `find_or_initialize_by'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/internal_metadata.rb:33:in `[]='
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/schema.rb:58:in `define'
     # /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/schema.rb:46:in `define'
     # ./spec/spec_helper.rb:112:in `schema_define'
     # ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb:10:in `block (2 levels) in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:360:in `instance_exec'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:360:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:524:in `block in run_owned_hooks_for'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:523:in `each'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:523:in `run_owned_hooks_for'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:475:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:553:in `block in run_before_context_hooks'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:552:in `run_before_context_hooks'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:605:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/exe/rspec:4:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/rspec:23:in `load'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/rspec:23:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /home/yahonda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
     # /home/yahonda/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
     # ------------------
     # --- Caused by: ---
     # OCIError:
     #   ORA-01805: possible error in date/time operation
     #   ocidatetime.c:119:in oci8lib_270.so

Finished in 1.33 seconds (files took 0.53585 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb:45 # OracleEnhancedAdapter timestamp with timezone support / TIMESTAMP WITH TIME ZONE values from ActiveRecord model should return Time value from TIMESTAMP columns
rspec ./spec/active_record/oracle_enhanced/type/timestamp_spec.rb:59 # OracleEnhancedAdapter timestamp with timezone support / TIMESTAMP WITH TIME ZONE values from ActiveRecord model should return Time value with fractional seconds from TIMESTAMP columns

$
```

### System configuration
**Rails version**:master branch

**Oracle enhanced adapter version**:master branch

**Ruby version**:ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Oracle Database version**:Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

**Oracle Client version**:Version 19.6.0.0.0

**Comment by yahonda** [comment]
This is due to timezone file version differences between 19.6 and 18.4, then usually we can upgrade timezone files manually.
However, then we are running Oracle Database using Docker on GitHub Actions, it is quite difficult to upgrade timezone files because it requires restarting Oracle database instance.

Another workaround is downgrading Oracle Instant Client Version 18.5.0.0.0, to install Oracle Instant Client Version 18.5 we need to be authorized to download them. I want to run Oracle enhanced adapter unit test at GitHub Actions, It would be appreciated if we can download Oracle Instant Client Version 18.5 without authorization/authentication.
