### ISSUE TITLE
Problems using ruby-oci8. Hook error: Could not replace function setsockopt

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#2056]
Stack:

```
RuntimeError:
  Hook error: Could not replace function setsockopt in /opt/oracle/product/19c/dbhome_1/lib/libclntsh.so.12.1
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/ruby-oci8-2.2.7/lib/oci8/properties.rb:74:in `__set_prop'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/ruby-oci8-2.2.7/lib/oci8/properties.rb:74:in `[]='
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:338:in `new_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:394:in `initialize'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:31:in `new'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:31:in `initialize'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:11:in `new'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:11:in `create'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-oracle_enhanced-adapter-6.0.4/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:74:in `oracle_enhanced_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
# /home/jlahtinen/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:189:in `connection'
```

Any ideas how to debug?

**Comment by jlahtinen** [comment]
Happens when connection fails. Has to do something with ruby-oci8. Trying to figure this out and report when clear
