### ISSUE TITLE
rails4: Needs support activerecord-session_store

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#213]
Now `activerecord-session_store` module has been separated from rails itself, Oracle enhanced adapter needs support it.

```ruby

$ rake spec
/home/yahonda/.rvm/rubies/ruby-1.9.3-p194/bin/ruby -S rspec ./spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_emulate_oracle_adapter_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_core_ext_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_dbms_output_spec.rb
==> Running specs with MRI version 1.9.3
==> Running specs with Rails version 4.0-master
/home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_session_store.rb:47:in `<top (required)>': uninitialized constant ActiveRecord::SessionStore (NameError)
        from /home/yahonda/git/oracle-enhanced/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1383:in `<top (required)>'
        from /home/yahonda/git/oracle-enhanced/spec/spec_helper.rb:32:in `require'
        from /home/yahonda/git/oracle-enhanced/spec/spec_helper.rb:32:in `<top (required)>'
        from /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb:1:in `require'
        from /home/yahonda/git/oracle-enhanced/spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb:1:in `<top (required)>'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `block in load_spec_files'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `map'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load_spec_files'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:22:in `run'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
        from /home/yahonda/.rvm/gems/ruby-1.9.3-p194@railsmaster/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
rake aborted!
/home/yahonda/.rvm/rubies/ruby-1.9.3-p194/bin/ruby -S rspec ./spec/active_record/connection_adapters/oracle_enhanced_cpk_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_procedures_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_structure_dump_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_schema_dump_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_schema_statements_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_connection_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_dirty_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_data_types_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_context_index_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_emulate_oracle_adapter_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_core_ext_spec.rb ./spec/active_record/connection_adapters/oracle_enhanced_dbms_output_spec.rb failed

Tasks: TOP => spec
(See full trace by running task with --trace)
$
```

This separation just for rails master branch, then it does not affect to current our master branch.
I'm working on this but not resolved it yet.

**Comment by yahonda** [comment]
Closing since it looks there is no request to support 'activerecord-session_store' for Oracle enhanced.
