### ISSUE TITLE
500 Internal Server Error   undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by megurushi** [rsim/oracle-enhanced#324]
Hi,
Can I get some help & advice on the following error:

	[2013-09-03 12:49:51.406] FATAL  /!\ FAILSAFE /!\  03 September 2013 12:49:51
	  Status: 500 Internal Server Error
	  undefined method `[]' for nil:NilClass
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-oracle_enhanced-adapter-1.2.4/lib/active_record/connection_adapters/oracle_
	enhanced_adapter.rb:713:in `write_lobs'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:42:in `
	uncached'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-oracle_enhanced-adapter-1.2.4/lib/active_record/connection_adapters/oracle_
	enhanced_adapter.rb:708:in `write_lobs'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-oracle_enhanced-adapter-1.2.4/lib/active_record/connection_adapters/oracle_
	enhanced_adapter.rb:703:in `each'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-oracle_enhanced-adapter-1.2.4/lib/active_record/connection_adapters/oracle_
	enhanced_adapter.rb:703:in `write_lobs'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-oracle_enhanced-adapter-1.2.4/lib/active_record/connection_adapters/oracle_
	enhanced_adapter.rb:105:in `enhanced_write_lobs'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:173:in `send'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:173:in `evaluate_method'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:161:in `call'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:93:in `run'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:92:in `each'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:92:in `send'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:92:in `run'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activesupport-2.1.2/lib/active_support/callbacks.rb:272:in `run_callbacks'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/callbacks.rb:298:in `callback'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/callbacks.rb:208:in `create_or_update'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/base.rb:2211:in `save_without_validation'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/validations.rb:911:in `save_without_dirty'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/dirty.rb:75:in `save_without_transactions'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/transactions.rb:106:in `save'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb
	:66:in `transaction'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/transactions.rb:79:in `transaction'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/transactions.rb:98:in `transaction'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/transactions.rb:106:in `save'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/transactions.rb:118:in `rollback_active_record_stat
	e!'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/transactions.rb:106:in `save'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/session/active_record_store.rb:314:in `update'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/activerecord-2.1.2/lib/active_record/base.rb:1267:in `silence'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/session/active_record_store.rb:314:in `update'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/session/active_record_store.rb:321:in `close'
		/opt/app/ruby/ruby/1.8.6-p399/lib/ruby/1.8/cgi/session.rb:326:in `close'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/base.rb:1235:in `close_session'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/base.rb:1271:in `process_cleanup_without_session_
	management_support'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/session_management.rb:140:in `process_cleanup_wit
	hout_components'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/components.rb:162:in `process_cleanup'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/base.rb:537:in `process_without_filters'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/filters.rb:568:in `process_without_session_manage
	ment_support'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/session_management.rb:130:in `sass_old_process'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/haml-3.0.25/rails/../lib/sass/plugin/rails.rb:27:in `process'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/base.rb:389:in `process'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/dispatcher.rb:149:in `handle_request'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/dispatcher.rb:107:in `dispatch'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/dispatcher.rb:104:in `synchronize'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/dispatcher.rb:104:in `dispatch'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/dispatcher.rb:120:in `dispatch_cgi'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/actionpack-2.1.2/lib/action_controller/dispatcher.rb:35:in `dispatch'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/railz/request_handler.rb:50:in `process_request'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:441:in `start_request_handler'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/utils.rb:252:in `safe_fork'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:163:in `start'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/railz/application_spawner.rb:222:in `start'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rails_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:247:in `spawn_rails_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rails_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:145:in `spawn_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/spawn_manager.rb:278:in `handle_spawn_application'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
		/opt/app/ruby/ruby/1.8.6-p399/gems/gems/passenger-2.2.15/bin/passenger-spawn-server:61

Many thanks

**Comment by yahonda** [comment]
Closing this issue due to inactivity. If it still reproduces please upgrade to the latest version of Rails and Oracle enhanced adapter.
