### ISSUE TITLE
Error on db:structure:dump and Oracle 11g - NoMethodError: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by rootatdarkstar** [rsim/oracle-enhanced#439]
jruby-1.7.11, rails 4.1, oracle 11g, oracle_enhanced 1.5.4

1) Schema.rb dumps well with only with one issue:

``` ruby
# Could not dump table "debug_lob" because of following StandardError
#   Unknown type 'SYS.XMLTYPE' for column 'xml'
```

2) No virtual columns in my base
3) After removing  table "debug_lob" error is gone.

Error

``` ruby
rake db:structure:dump --trace
** Invoke db:structure:dump (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:structure:dump
rake aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-oracle_enhanced-adapter-1.5.4/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb:58:in `structure_dump_virtual_column'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-oracle_enhanced-adapter-1.5.4/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb:26:in `structure_dump'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-4.1.0/lib/active_record/result.rb:55:in `each'
org/jruby/RubyArray.java:1613:in `each'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-4.1.0/lib/active_record/result.rb:55:in `each'
org/jruby/RubyEnumerable.java:763:in `map'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-oracle_enhanced-adapter-1.5.4/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb:22:in `structure_dump'
org/jruby/RubyArray.java:1613:in `each'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-oracle_enhanced-adapter-1.5.4/lib/active_record/connection_adapters/oracle_enhanced_structure_dump.rb:12:in `structure_dump'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-oracle_enhanced-adapter-1.5.4/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:42:in `structure_dump'
org/jruby/RubyIO.java:1182:in `open'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-oracle_enhanced-adapter-1.5.4/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:42:in `structure_dump'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-4.1.0/lib/active_record/tasks/database_tasks.rb:150:in `structure_dump'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/activerecord-4.1.0/lib/active_record/railties/databases.rake:269:in `(root)'
org/jruby/RubyProc.java:271:in `call'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/task.rb:235:in `execute'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/task.rb:179:in `invoke_with_call_chain'
/home/authorised/.rvm/rubies/jruby-1.7.11/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/task.rb:165:in `invoke'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:150:in `invoke_task'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:106:in `top_level'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:115:in `run_with_threads'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:100:in `top_level'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:78:in `run'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/lib/rake/application.rb:75:in `run'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/gems/rake-10.3.0/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1101:in `load'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/bin/rake:1:in `(root)'
org/jruby/RubyKernel.java:1121:in `eval'
/home/authorised/.rvm/gems/jruby-1.7.11@ilp-app/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => db:structure:dump
```

**Comment by scottschulthess** [comment]
@rootatdarkstar 
xmltype under the hood is a virtual column, see
The XMLType column itself becomes a virtual column over this hidden CLOB column. It is not possible to directly access the CLOB column; however, you can set the storage characteristics for the column using the XMLType storage clause.
http://docs.oracle.com/cd/B10501_01/appdev.920/a96620/xdb04cre.htm
