### ISSUE TITLE
Argument error in oracle_enhanced_dirty when running migrations on Rails 4.2

### ISSUE THREAD

**Issue by emerson-h** [rsim/oracle-enhanced#477]
When running a migration on Rails4.2.beta1, an argument error is raised in oracle_enhanced_dirty

rake aborted!
StandardError: An error has occurred, all later migrations canceled:

```
wrong number of arguments (2 for 3)/Users/emerson-huitt/.rvm/gems/ruby-2.1.2/bundler/gems/oracle-enhanced-3fcba4e17f51/lib/active_record/connection_adapters/oracle_enhanced_dirty.rb:8:in `_field_changed?'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_methods/dirty.rb:101:in `save_changed_attribute'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_methods/dirty.rb:85:in `write_attribute'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_methods.rb:49:in `__temp__6756273796f6e6'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:54:in `public_send'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:35:in `each'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/core.rb:543:in `init_attributes'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/core.rb:264:in `initialize'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/inheritance.rb:61:in `new'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/inheritance.rb:61:in `new'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/persistence.rb:50:in `create!'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:1019:in `record_version_state_after_migrating'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:989:in `block in execute_migration_in_transaction'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:1036:in `ddl_transaction'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:987:in `execute_migration_in_transaction'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:949:in `block in migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:945:in `each'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:945:in `migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:817:in `up'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:795:in `migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:135:in `migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:242:in `load'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:242:in `block in load'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:242:in `load'
-e:1:in `<main>'
ArgumentError: wrong number of arguments (2 for 3)
.rvm/gems/ruby-2.1.2/bundler/gems/oracle-enhanced-3fcba4e17f51/lib/active_record/connection_adapters/oracle_enhanced_dirty.rb:8:in `_field_changed?'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_methods/dirty.rb:101:in `save_changed_attribute'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_methods/dirty.rb:85:in `write_attribute'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_methods.rb:49:in `__temp__6756273796f6e6'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:54:in `public_send'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:35:in `each'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/core.rb:543:in `init_attributes'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/core.rb:264:in `initialize'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/inheritance.rb:61:in `new'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/inheritance.rb:61:in `new'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/persistence.rb:50:in `create!'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:1019:in `record_version_state_after_migrating'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:989:in `block in execute_migration_in_transaction'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:1036:in `ddl_transaction'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:987:in `execute_migration_in_transaction'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:949:in `block in migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:945:in `each'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:945:in `migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:817:in `up'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:795:in `migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:135:in `migrate'
.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:242:in `load'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:242:in `block in load'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:242:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by yahonda** [comment]
Closed as #479 has been merged to rails42 branch.
