### ISSUE TITLE
rails 4.2.0.rc1 failed to do assets:precompile

### ISSUE THREAD

**Issue by Eric-Guo** [rsim/oracle-enhanced#523]
Using rails 4.2.0.rc1 and oracel-enhanced rails42 branch.

But known works well at 4.2.0.beta4, and I replace the activerecord 4.2.0.beta4 version and works find, so must be some change in activerecord cause below error.

```
mveletst@cvprcsip01:~/releases/20141129012400$ bundle exec rake assets:precompile
rake aborted!
TypeError: superclass mismatch for class OracleEnhancedAdapter
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:221:in `<module:ConnectionAdapters>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:158:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:141:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/activerecord-oracle_enhanced-adapter.rb:12:in `block in <class:OracleEnhancedRailtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/base.rb:316:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0.rc1/lib/active_record/base.rb:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:5:in `<class:DatabaseTasks>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:4:in `<class:OracleEnhancedAdapter>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:3:in `<module:ConnectionAdapters>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:2:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/active_record/connection_adapters/oracle_enhanced_database_tasks.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/activerecord-oracle_enhanced-adapter.rb:8:in `load'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-0ab103a4ee88/lib/activerecord-oracle_enhanced-adapter.rb:8:in `block in <class:OracleEnhancedRailtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/railtie.rb:237:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/railtie.rb:237:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/railtie.rb:245:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/railtie.rb:245:in `each_registered_block'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/railtie.rb:237:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/application.rb:437:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/engine/railties.rb:13:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/engine/railties.rb:13:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/application.rb:437:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0.rc1/lib/rails/engine.rb:453:in `load_tasks'
/home/mveletst/releases/20141129012400/Rakefile:6:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by lustremedia** [comment]
Does not work for rails 4.1.10 either, which was released with the latest rails 4.2

Using activesupport (4.1.10)
Using activemodel (4.1.10)
Using activerecord (4.1.10)
Using activerecord-oracle_enhanced-adapter (1.5.5)

What is the fix I need to apply?

**Comment by lustremedia** [comment]
Is it advised to use ```gem "activerecord-oracle_enhanced-adapter" "http://github.com/rsim/oracle-enhanced.git"``` in productive environments to fix this issue?

**Comment by yahonda** [comment]
Thanks for the reporting. #530 includes a fix for `master` branch. Going to release Oracle enhanced adapter 1.5.6 to support Rails 4.1.10.

**Comment by lustremedia** [comment]
@yahonda I opened #567 for my issue in case you did not notice.
