### ISSUE TITLE
Rails 4.2 "undefined method `[]' for TestEmployee(Table doesn't exist):Class" 

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#524]
Since https://github.com/rails/arel/commit/7508284800f67b4611c767bff9eae7045674b66f 172 tests get "undefined method `[]' for TestEmployee(Table doesn't exist):Class" or similar errors,
only model names are different based on test cases.

```ruby
Rails `4-2-stable` branch
Arel `master` branch
Oracle enhanced adapter `rails42` branch
```

Here is a one of rspec testcases.

```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:82
==> Running specs with MRI version 2.2.0
==> Running specs with Rails version 4.0-master
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[82]}}
F

Failures:

  1) OracleEnhancedAdapter ignore specified table columns should ignore specified table columns
     Failure/Error: ignore_table_columns  :phone_number, :hire_date
     NoMethodError:
       undefined method `[]' for TestEmployee(Table doesn't exist):Class
     # /home/yahonda/git/rails/activerecord/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
     # /home/yahonda/git/arel/lib/arel/table.rb:22:in `initialize'
     # /home/yahonda/git/rails/activerecord/lib/active_record/core.rb:238:in `new'
     # /home/yahonda/git/rails/activerecord/lib/active_record/core.rb:238:in `arel_table'
     # /home/yahonda/git/rails/activerecord/lib/active_record/model_schema.rb:150:in `table_name='
     # /home/yahonda/git/rails/activerecord/lib/active_record/model_schema.rb:160:in `reset_table_name'
     # /home/yahonda/git/rails/activerecord/lib/active_record/model_schema.rb:126:in `table_name'
     # ./lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:52:in `ignore_table_columns'
     # ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:84:in `<class:TestEmployee>'
     # ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:83:in `block (3 levels) in <top (required)>'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:116:in `block in run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:248:in `with_around_each_hooks'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:113:in `run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:515:in `block in run_examples'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `map'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `run_examples'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:496:in `run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `block in run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `map'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block (2 levels) in run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `map'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block in run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/reporter.rb:58:in `report'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:21:in `run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
     # /home/yahonda/.rvm/gems/ruby-head@rails42/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'

Finished in 0.18394 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:82 # OracleEnhancedAdapter ignore specified table columns should ignore specified table columns
$
```

**Comment by yahonda** [comment]
Closed since it does not reproduce anymore.
