### ISSUE TITLE
Includes returning nil values

### ISSUE THREAD

**Issue by reejosamuel** [rsim/oracle-enhanced#554]
Includes is returning is nil. Im not able to figure out from the trace what is causing this issue. When i remove the includes it seems to work. 

The same code is working with `jRuby` and `activerecord-jdbc`
Controller
```
@posts = Post.includes(:author).all.order(:created_at)
```

`Post` Model 
```
class Post < ActiveRecord::Base
  belongs_to :author
end
```

View
```
....
if @posts.length > 0
 @posts.each do |post|
  ...
  end
end
....
```

Returns the error
```
NoMethodError: undefined method `each' for nil:NilClass
```

```
NoMethodError - undefined method `each' for nil:NilClass:
  activerecord (4.1.5) lib/active_record/associations/preloader/association.rb:93:in `block in associated_records_by_owner'
  activerecord (4.1.5) lib/active_record/associations/preloader/association.rb:92:in `associated_records_by_owner'
  activerecord (4.1.5) lib/active_record/associations/preloader/singular_association.rb:9:in `preload'
  activerecord (4.1.5) lib/active_record/associations/preloader/association.rb:20:in `run'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:137:in `block (2 levels) in preloaders_for_one'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:135:in `block in preloaders_for_one'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:134:in `preloaders_for_one'
  activerecord (4.1.5) lib/active_record/associations/preloader.rb:106:in `preloaders_on'
  bullet (4.14.0) lib/bullet/active_record41.rb:35:in `preloaders_on'
  squeel (1.2.2) lib/squeel/adapters/active_record/4.1/preloader_extensions.rb:21:in `block in preload_with_squeel'
  squeel (1.2.2) lib/squeel/adapters/active_record/4.1/preloader_extensions.rb:20:in `preload_with_squeel'
  activerecord (4.1.5) lib/active_record/relation.rb:610:in `block in exec_queries'
  activerecord (4.1.5) lib/active_record/relation.rb:609:in `exec_queries'
  activerecord (4.1.5) lib/active_record/relation.rb:486:in `load'
  activerecord (4.1.5) lib/active_record/relation.rb:231:in `to_a'
  bullet (4.14.0) lib/bullet/active_record41.rb:10:in `to_a'
  will_paginate (3.0.7) lib/will_paginate/active_record.rb:134:in `block in to_a'
  will_paginate (3.0.7) lib/will_paginate/collection.rb:96:in `create'
  will_paginate (3.0.7) lib/will_paginate/active_record.rb:133:in `to_a'
  activerecord (4.1.5) lib/active_record/relation/delegation.rb:46:in `length'
   () Users/reejosamuel/Documents/rails/source/demoapp/app/views/posts/index.html.erb:21:in `_app_views_posts_index_html_erb___2735640742406789384_70114378574360'
  actionview (4.1.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.5) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.5) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.5) lib/action_view/template.rb:143:in `render'
  actionview (4.1.5) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.5) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.5) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.5) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.5) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.5) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.5) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.5) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.5) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.5) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.5) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.5) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.5) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.5) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.5) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.5) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.5) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
   () Users/reejosamuel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.1.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.5) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.5) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.5) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.5) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (4.1.5) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.1.5) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.1.5) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.5) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.5) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.5) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.5) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:299:in `block (2 levels) in halting'
  rails-observers (0.1.2) lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
  activesupport (4.1.5) lib/active_support/callbacks.rb:447:in `block in make_lambda'
  activesupport (4.1.5) lib/active_support/callbacks.rb:298:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.5) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.5) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.5) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.5) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.5) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.5) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.5) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.5) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.5) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.5) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.5) lib/action_dispatch/routing/route_set.rb:678:in `call'
  bullet (4.14.0) lib/bullet/rack.rb:12:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.5) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.5) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.5) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.1.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.5) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.5) lib/rails/engine.rb:514:in `call'
  railties (4.1.5) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  webrick (1.3.1) lib/webrick/httpserver.rb:138:in `service'
  webrick (1.3.1) lib/webrick/httpserver.rb:94:in `run'
  webrick (1.3.1) lib/webrick/server.rb:191:in `block in start_thread'
```

**Comment by yahonda** [comment]
Thanks for reporting. Closing this this stack trace does not contain Oracle enhanced adapter related entries.
