### ISSUE TITLE
Mixing Postgres and Oracle adapter seems to cause some problems when running migrations

### ISSUE THREAD

**Issue by matthewcrawford** [rsim/oracle-enhanced#561]
I'm using a system which is primarily using Postgres as a database, but need the Oracle adapter to pull data from a foreign database.  It seems, though, that the Oracle adapter keeps getting pulled into service even when the models aren't part of the Oracle schema (and the main database connection in database.yml is set to the postgres adapter.

In the most recent incarnation of the problem, I'm running into problems running migrations that don't concern the oracle adapter:
NoMethodError: undefined method `size' for nil:NilClass
/Users/Matt1/.rvm/gems/ruby-2.1.2/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:66:in `block in foreign_keys_with_oracle_enhanced'

Oracle Adapter: gem 'activerecord-oracle_enhanced-adapter', :git=> 'https://github.com/rsim/oracle-enhanced.git', branch: 'rails42'

Rails: Rails 4.2.0
Ruby:ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

**Comment by yahonda** [comment]
Please update at least these information.

- Oracle enhanced adapter version
- Rails version
- Ruby version

Thanks

**Comment by jamgregory** [comment]
We've just encountered this same issue while migrating our primary Postgres database to include extra information in one of the tables. The migration worked correctly, but then failed at the schema dump stage with the following stacktrace:

```
rake aborted!
NoMethodError: undefined method `size' for nil:NilClass
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-654656f7c124/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:66:in `block in foreign_keys_with_oracle_enhanced'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-654656f7c124/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:62:in `map'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-654656f7c124/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:62:in `foreign_keys_with_oracle_enhanced'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:103:in `block in tables'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:102:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:102:in `tables'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-654656f7c124/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb:28:in `tables_with_oracle_enhanced'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:38:in `dump'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/schema_dumper.rb:22:in `dump'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:237:in `block (4 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:236:in `open'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:236:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:50:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump
```

The Oracle enhanced adapter version is 1.5.6 654656f (from the rails42 branch), Rails version is 4.2.1 and Ruby version is 2.1.5.

**Comment by yahonda** [comment]
Would you guys give it a try by adding this entry to your Gemfile.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'rails42_fk_with_other_adapters' 
```

**Comment by jamgregory** [comment]
Hi @yahonda. I've given that a try now, and the ``size`` issue seems to be fixed, but I've come across another issue now while running the migrations:

```
NoMethodError: undefined method `add_index' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x000000035d60a8>
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-2ad52d337089/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:97:in `block in references_with_foreign_keys'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-2ad52d337089/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:95:in `each'
/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/oracle-enhanced-2ad52d337089/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:95:in `references_with_foreign_keys'
/{path to migrate folder}/20150416144344_{migration name}.rb:4:in `block in change'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:202:in `create_table'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/{path to migrate folder}/20150416144344_{migration name}.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by yahonda** [comment]
@jamgregory Thanks for testing. Would you test to see if you can reproduce `NoMethodError: undefined method `add_index'` using the latest `rails42` branch.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'rails42' 
```

**Comment by jamgregory** [comment]
Hi @yahonda, sorry for the delay in replying. I've just checked the latest `rails42` branch, and the migrations seemed to work without a problem - the `add_index` issue appears to be fixed.

**Comment by yahonda** [comment]
@jamgregory Thanks for testing. Good to know.
