### ISSUE TITLE
SQLite ActiveRecord objects won't create when using Oracle Enhanced Adapter

### ISSUE THREAD

**Issue by comtesacristain** [rsim/oracle-enhanced#590]
Hi

I'm getting an error whenever I try to create ActiveRecord objects in a local SQLite database in tandem with an Oracle database. Configuration is as follows:

## Gemfile
```ruby
...
gem 'sqlite3'

gem 'ruby-oci8'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.5.0'
...
```

## database.yml
```yaml
local:
  adapter: sqlite3
  database: db/local.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: oracle_enhanced
  database: 'server:port/service_name'
  username: user
  password: password

```
## duplicate.rb
```ruby
class Duplicate < ActiveRecord::Base
  establish_connection :local
end

```

## Console

```ruby
Loading development environment (Rails 4.2.1)
irb(main):001:0> d=Duplicate.new
=> #<Duplicate id: nil, eno: nil, entity_type: nil, entityid: nil, x: nil, y: nil, z: nil, has_well: nil, has_samples: nil, no_samples: nil, action: nil, duplicate_group_id: nil, created_at: nil, updated_at: nil>
irb(main):002:0> d.entityid="Test"
```

## Error
```
ArgumentError: wrong number of arguments (2 for 3)
        from /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_dirty.rb:8:in `_field_changed?'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:114:in `save_changed_attribute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:98:in `write_attribute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/attribute_methods/write.rb:43:in `__temp__56e6479647979646='
        from (irb):2
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /nas/oemd/mra/group/users/mgsexton/ruby/ruby-rdis/bin/rails:8:in `<top (required)>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/commands/rails.rb:6:in `call'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/command_wrapper.rb:38:in `call'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application.rb:183:in `block in serve'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application.rb:156:in `fork'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application.rb:156:in `serve'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application.rb:131:in `block in run'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application.rb:125:in `loop'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application.rb:125:in `run'
        from /usr/local/lib/ruby/gems/1.9.1/gems/spring-1.3.5/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from -e:1:in `<main>'
```

This error persists even if I do not use `oracle_enhanced` as my adapter in my `database.yml` file, and only seems to disappear once I comment out the `activerecord-oracle_enhanced-adapter` gem in the `Gemfile`.

I'm using Rails 4.2.1 and Oracle Enhanced Adapter 1.5.6

Thanks

Michael

**Comment by Daniel304** [comment]
try using oracle_enhanced the rails42 branch:
gem 'activerecord-oracle_enhanced-adapter', :git => "http://github.com/rsim/oracle-enhanced.git", :branch => "rails42"

**Comment by yahonda** [comment]
Closed. Rails 4.2 requires Oracle enhanced adapter branch `rails42` as suggested.

```ruby
gem 'activerecord-oracle_enhanced-adapter', :git => "http://github.com/rsim/oracle-enhanced.git", :branch => "rails42"
```
Thanks
