### ISSUE TITLE
Legacy schema support

### ISSUE THREAD

**Issue by DemidenkoAndrey** [rsim/oracle-enhanced#609]
When I try to create or select record, for example:
```ruby 
Client.new
```
results in error:
```ruby
NoMethodError: undefined method `without_prepared_statement?' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x000000054d0dc8>: SELECT column_name AS name, data_type AS sql_type, data_default, nullable, virtual_column, hidden_column, data_type_owner AS sql_type_owner, DECODE(data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale FROM all_tab_cols WHERE owner = 'ADMIN' AND table_name = 'CLIENTS' AND hidden_column = 'NO' ORDER BY column_id
ActiveRecord::StatementInvalid: NoMethodError: undefined method `without_prepared_statement?' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x000000054d0dc8>: SELECT column_name AS name, data_type AS sql_type, data_default, nullable, virtual_column, hidden_column, data_type_owner AS sql_type_owner, DECODE(data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale FROM all_tab_cols WHERE owner = 'ADMIN' AND table_name = 'CLIENTS' AND hidden_column = 'NO' ORDER BY column_id
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:28:in `block in exec_query'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:425:in `block in log'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:420:in `log'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1261:in `log'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:25:in `exec_query'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:253:in `select'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1036:in `columns_without_cache'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-oracle_enhanced-adapter-1.5.6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1005:in `columns'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:114:in `block in prepare_default_proc'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:56:in `yield'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/model_schema.rb:208:in `columns'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/model_schema.rb:242:in `column_defaults'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/locking/optimistic.rb:169:in `column_defaults'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/core.rb:181:in `initialize'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/inheritance.rb:27:in `new'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.0.0/lib/active_record/inheritance.rb:27:in `new'
        from (irb):1
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
        from bin/rails:4:in `require'

```

**Comment by yahonda** [comment]
Would you upgrade Rails version to 4.1(recommended) or higher or use Oracle enhanced adapter 1.5.4 (I do not recommend though)?

**Comment by yahonda** [comment]
Closing this issue since no feedback available.

**Comment by DemidenkoAndrey** [comment]
@yahonda  Sorry, Your answer was very helpful

**Comment by yahonda** [comment]
no problem. Thanks for the feedback.
