### ISSUE TITLE
OCIError ORA-06413: Connection not open on Rails 4.2.3, Ruby 2.1.6 an Passenger 5 with Apache

### ISSUE THREAD

**Issue by 341bms** [rsim/oracle-enhanced#684]
If the app is running on Passenger 4 (GEM) everything ist okay. If the same App runs on Passenger 5 (APT install) I run into the following error:

```
OCIError (ORA-06413: Connection not open.):
  oci8.c:656:in oci8lib_210.so
  ruby-oci8 (2.1.8) lib/oci8/oci8.rb:148:in `initialize'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:330:in `new'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:330:in `new_connection'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:389:in `initialize'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:26:in `new'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:26:in `initialize'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/connection.rb:9:in `new'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced/connection.rb:9:in `create'
  activerecord-oracle_enhanced-adapter (1.6.1) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:156:in `oracle_enhanced_connection'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /home/deploy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /home/deploy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.3) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.3) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.3) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.2.3) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:31:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

Another App (Rails 3.2, activerecord-oracle_enhanced-adapter 1.5.x) runs on both v4 and v5 versions of Passenger without problems. Does anyone experienced the same? Any suggestions?

**Comment by yahonda** [comment]
I have never seen ORA-06413 error. Would you confirm this readme and all environment values are configured under your Passenger 5 environment.

https://github.com/rsim/oracle-enhanced#what-to-do-if-oracle-enhanced-adapter-is-not-working-with-phusion-passenger

**Comment by 341bms** [comment]
LD_LIBRARY_PATH and NLS_LANG are both set in the global .profile + in the Apache envvars file + via SetEnv in the Vhost configuration. 
A Rails 3.2 App with activerecord-oracle_enhanced-adapter runs on the same Passenger 5 server without problems. 
Both Apps (Rails 3.2 and Rails 4.2, both with activerecord-oracle_enhanced-adapter) are running under Passenger 4 without problems.

**Comment by yahonda** [comment]
Thanks for the update. 

ORA-06413 is connection related ones then please confirm `TNS_ADMIN` has been successfully configured to point the directory where `tnsnames.ora` file exists. Unfortunately I have no other clue, hope someone have some suggestions.

**Comment by 341bms** [comment]
After installing the Ruby-oci8 against a 12.1 Oracle Instant Client everything works again. Before it was Oracle Instant Client 10.1. Only `LD_LIBRARY_PATH` and `NLS_LANG` are needed in the env. 

Still not knowing the real reason, but it works for now. Thanks for your time and assistence!

**Comment by yahonda** [comment]
Thanks for the update.
