### ISSUE TITLE
undefined method `write' for nil:NilClass

### ISSUE THREAD

**Issue by KKirad** [rsim/oracle-enhanced#762]
```ruby
NoMethodError: undefined method `write' for nil:NilClass
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-oracle_enhanced-adapter-1.6.0/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:211:in `write_lob'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-oracle_enhanced-adapter-1.6.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:837:in `block (2 levels) in write_lobs'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:49:in `uncached'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-oracle_enhanced-adapter-1.6.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:830:in `block in write_lobs'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-oracle_enhanced-adapter-1.6.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:825:in `each'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-oracle_enhanced-adapter-1.6.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:825:in `write_lobs'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-oracle_enhanced-adapter-1.6.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:132:in `enhanced_write_lobs'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
... 29 levels...
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block in save'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.0/lib/active_record/transactions.rb:285:in `save'
from (irb):3
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /home/kalyani/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
```
While saving my model this i am getting this error.
Using Ruby version: ruby-2.0.0-p598
Using Rails version '4.2.0'
Issue is reproduced with activerecord-oracle_enhanced-adapter version: 1.6.0 - 1.6.6

**Comment by KKirad** [comment]
As per the Changes and bug fixes since 1.6.1 
https://github.com/rsim/oracle-enhanced/blob/master/History.md

Oracle enhanced adapter v1.6 requires ActiveRecord 4.2.1 or higher, ActiveRecord 4.2.0 is not supported.[#672]

However, i tried with lower version for Oracle enhanced adapter as well as higher.

**Comment by yahonda** [comment]
Would you update the exact test case and stack trace using the latest Rails 4.2.5 and Oracle enhanced adapter 1.6.6. Thanks,

**Comment by KKirad** [comment]
I updated Rails version to 4.2.5 and Oracle enhanced adapter 1.6.6 and the issue is not reproduced. Thanks.

**Comment by yahonda** [comment]
Thanks for the testing and reporting. Glad you have resolved this issue.
