### ISSUE TITLE
RangeError: bignum too big to convert into `long'

### ISSUE THREAD

**Issue by sliminas** [rsim/oracle-enhanced#793]
I get an error on this [Line](https://github.com/rsim/oracle-enhanced/blob/00dbea2885aeeb1edca8f3f70c92b97bc685a8d0/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb#L333) with Bignums.

The Problem is that Javas Long [MAX_VALUE](http://docs.oracle.com/javase/6/docs/api/java/lang/Long.html#MAX_VALUE) is 2^63-1 which is a Fixnum in Ruby.
2^63 is a Bignum which is also an Integer, but when executing 

``` ruby
@raw_statement.setLong(position, java_value)
```

with java_value 2^63 or higher I'll get the RangeError: bignum too big to convert into `long'.

Probably there should happen something like this:

``` ruby
case value
when Fixnum
  @raw_statement.setLong(position, java_value)
when Bignum
   # do sth else
when Float 
   #.....
```

rails 4.2.5
JRuby 1.7.22
activerecord-oracle_enhanced-adapter 1.6.7
ojdbc6

**Comment by yahonda** [comment]
Thanks for reporting. Would you create your testcase to reproduce this including exact number` you are using.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 4.2.0'
  gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
  end

  create_table :comments, :force => true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id
  end
end
```

**Comment by sliminas** [comment]
Here is the testcase. It works as excpected when changing the last digit of the id to 7 (9223372036854775807).

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 4.2.0'
  gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
  end

  create_table :comments, :force => true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    Post.create!
    assert_nil Post.find_by_id(9223372036854775808)
  end
end
```

**Comment by yahonda** [comment]
Thanks for providing the test case.
Let me confirm that you are using JRuby since I do not reproduce it using ruby 2.3 (MRI).


```ruby
  1) Error:
BugTest#test_association_stuff:
ActiveRecord::StatementInvalid: RangeError: bignum too big to convert into `long': SELECT  "POSTS".* FROM "POSTS" WHERE "POSTS"."ID" = :a1 AND ROWNUM <= 1
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/jdbc_connection.rb:333:in `bind_param'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:37:in `block in exec_query'
    org/jruby/RubyArray.java:1560:in `each'
    org/jruby/RubyEnumerable.java:1016:in `each_with_index'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:35:in `block in exec_query'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1353:in `log'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:23:in `exec_query'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1313:in `select'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/querying.rb:39:in `find_by_sql'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/statement_cache.rb:107:in `execute'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/core.rb:187:in `find_by'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/dynamic_matchers.rb:70:in `find_by_id'
    /home/yahonda/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/gems/activerecord-4.2.6/lib/active_record/dynamic_matchers.rb:24:in `method_missing'
    rep.rb:64:in `test_association_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
jruby-9.0.5.0 [~/work/rep793]$
```

**Comment by sliminas** [comment]
Yes I'm using JRuby 1.7.22 and get the same error as above instead of the expected nil value.
