### ISSUE TITLE
NoMethodError: undefined method `write' for nil:NilClass for serialized column

### ISSUE THREAD

**Issue by Bjoernsen** [rsim/oracle-enhanced#798]
I am not sure, but I might have found a :bug: 

I have a table where I would like to have a column to store an Array.

So I added let's say `dents` to `cars`.
```ruby
class AddDentsToCar < ActiveRecord::Migration
  def change
    add_column :cars, :dents, :text
  end
end
```

Then, I modified the `Car` class to handle the serialization of the Array for me.
```ruby
class Cars < ActiveRecord::Base
  serialize :dents, Array
end
```

In principle, it works. I am able to play around with my `dents` Array. The issue is that I am not able to store an empty `Array` in the DB.
```ruby
car = Car.first
car.dents # => []
car.dents << 'street-lamp'
car.dents # => ['street-lamp']
car.save! # => true

car = Car.first
car.dents # => ['street-lamp']
car.dents = []
car.save! # => NoMethodError: undefined method `write' for nil:NilClass
```

For my Issue, I found a solution. But I do not know, if it breaks the adapter :smirk: 

I changed the line 828 in `oracle_enhanced_adapter.rb`, see
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L828

from
```ruby
next if value.nil?  || (value == '')
```

to
```ruby
next if value.blank?
```

Now, it works as expected.
```ruby
car = Car.first
car.dents # => ['street-lamp']
car.dents = []
car.save! # =>true

car = Car.first
car.dents # => []
```

Environment
- ruby: `2.3.0`
- rails: `4.2.6`
- activerecord-oracle_enhanced-adapter: `1.6.7`

The log

```ruby
NoMethodError: undefined method `write' for nil:NilClass
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:213:in `write_lob'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:838:in `block (2 levels) in write_lobs'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:49:in `uncached'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:830:in `block in write_lobs'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:825:in `each'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:825:in `write_lobs'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:132:in `enhanced_write_lobs'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `block in call'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `each'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `call'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:310:in `_update_record'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activerecord-4.2.6/lib/active_record/timestamp.rb:70:in `_update_record'
... 24 levels...
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/bjoernsen/Documents/coding/git/DentCars/bin/rails:8:in `<top (required)>'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@dent_cars/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/bjoernsen/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bjoernsen/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by negativalpha** [comment]
Haven't checked `1.6.7`, but I'm experiencing the same issue with `1.6.6`. This happens when the serialized column (that's already stored in the database) is NULL.

**Comment by Bjoernsen** [comment]
The line number has been changed. Now it is https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb#L703

in the method
```ruby
def write_lobs(table_name, klass, attributes, columns)
```

**Comment by coreypmurphy** [comment]
+1 for this issue.  Doing the same as OP.  Serializing an array and persisting results in same error when array is empty.

ruby: 2.2.2
rails: 4.2.5
activerecord-oracle_enhanced-adapter: 1.6.7
