### ISSUE TITLE
Rails 5 : undefined method `to_i' for #<Arel::Nodes::BindParam:0x00000002c92910>

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#848]
```ruby
$ rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:741
==> Loading config from ENV or use default
==> Running specs with MRI version 2.3.0
==> Effective ActiveRecord version 5.1.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[741]}}
F

Failures:

  1) OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n)
     Failure/Error: expect(@employee.order(:sort_order).offset(0).first.first_name).to eq("Peter")

     NoMethodError:
       undefined method `to_i' for #<Arel::Nodes::BindParam:0x00000002c92910>
       Did you mean?  to_s
                      to_h
                      to_a
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/arel-6d2254ae4ac5/lib/arel/visitors/oracle.rb:30:in `visit_Arel_Nodes_SelectStatement'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/arel-6d2254ae4ac5/lib/arel/visitors/reduce.rb:13:in `visit'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/arel-6d2254ae4ac5/lib/arel/visitors/reduce.rb:7:in `accept'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/connection_adapters/determine_if_preparable_visitor.rb:8:in `accept'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/querying.rb:39:in `find_by_sql'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation.rb:694:in `exec_queries'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation.rb:575:in `load'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation.rb:260:in `records'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation.rb:256:in `to_a'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation/finder_methods.rb:561:in `find_nth_with_limit'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation/finder_methods.rb:590:in `find_nth_with_limit_and_offset'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation/finder_methods.rb:543:in `find_nth'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bundler/gems/rails-ff4986b917f6/activerecord/lib/active_record/relation/finder_methods.rb:122:in `first'
     # ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:743:in `block (3 levels) in <top (required)>'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:236:in `instance_exec'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:236:in `block in run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:478:in `block in with_around_and_singleton_context_hooks'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:435:in `block in with_around_example_hooks'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:478:in `block in run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:478:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:435:in `with_around_example_hooks'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:478:in `with_around_and_singleton_context_hooks'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:233:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:581:in `block in run_examples'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:577:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:577:in `run_examples'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:543:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:544:in `block in run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:544:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:544:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
     # /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Finished in 0.60933 seconds (files took 0.63341 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:741 # OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n)
$
```

* Environment
```ruby
ActiveRecord Oracle enhanced adapter `rails5` branch
Rails master branch
Oracle Database 11g XE
```

It does not reproduce with Oracle Database 12c database since it uses Oracle12 visitor.

**Comment by yahonda** [comment]
Here are rspec statment and expected sql statements generated based on Rails 4.2 and Oracle enhanced adapter 1.6.7.

```ruby
expect(@employee.order(:sort_order).offset(0).first.first_name.should).to eq("Peter")
```

```sql
SELECT * FROM (
  SELECT raw_sql_.*, rownum raw_rnum_
  FROM (SELECT  "TEST_EMPLOYEES".* FROM "TEST_EMPLOYEES"  ORDER BY "TEST_EMPLOYEES"."SORT_ORDER" ASC ) raw_sql_
  WHERE rownum <= 1
)
WHERE raw_rnum_ > 0
```

```ruby
expect(@employee.order(:sort_order).offset(1).first.first_name.should).to eq("Tony")
```

```sql
SELECT * FROM (
  SELECT raw_sql_.*, rownum raw_rnum_
  FROM (SELECT  "TEST_EMPLOYEES".* FROM "TEST_EMPLOYEES"  ORDER BY "TEST_EMPLOYEES"."SORT_ORDER" ASC ) raw_sql_
  WHERE rownum <= 2
)
WHERE raw_rnum_ > 1
```

```ruby
expect(@employee.order(:sort_order).offset(4).first.first_name.should).to eq("Natasha")
```

```sql
SELECT * FROM (
  SELECT raw_sql_.*, rownum raw_rnum_
  FROM (SELECT  "TEST_EMPLOYEES".* FROM "TEST_EMPLOYEES"  ORDER BY "TEST_EMPLOYEES"."SORT_ORDER" ASC ) raw_sql_
  WHERE rownum <= 5
)
WHERE raw_rnum_ > 4
```

**Comment by yahonda** [comment]
Closing it since it has been addressed by https://github.com/rails/arel/pull/450
