### ISSUE TITLE
 uninitialized constant ActiveRecord::ConnectionAdapters::OracleEnhancedColumn::FALSE_VALUES (NameError)

### ISSUE THREAD

**Issue by thiaguerd** [rsim/oracle-enhanced#889]
```ruby
from */gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/column.rb:2:in '<module:ActiveRecord>'
from */gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced/column.rb:1:in '<top (required)>'
from */gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:39:in '<top (required)>'
from */gems/activerecord-oracle_enhanced-adapter-1.6.7/lib/activerecord-oracle_enhanced-adapter.rb:12:in 'block in <class:OracleEnhancedRailtie>'
from */gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in 'instance_eval'
from */gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in 'execute_hook'
from */gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in 'block in run_load_hooks'
from */gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in 'each'
from */gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in 'run_load_hooks'
from */gems/activerecord-5.0.0/lib/active_record/base.rb:324:in '<module:ActiveRecord>'
from */gems/activerecord-5.0.0/lib/active_record/base.rb:24:in '<top (required)>'
from */gems/spring-1.7.2/lib/spring/application.rb:338:in 'active_record_configured?'
from */gems/spring-1.7.2/lib/spring/application.rb:259:in 'disconnect_database'
from */gems/spring-1.7.2/lib/spring/application.rb:97:in 'preload'
from */gems/spring-1.7.2/lib/spring/application.rb:143:in 'serve'
from */gems/spring-1.7.2/lib/spring/application.rb:131:in 'block in run'
from */gems/spring-1.7.2/lib/spring/application.rb:125:in 'loop'
from */gems/spring-1.7.2/lib/spring/application.rb:125:in 'run'
from */gems/spring-1.7.2/lib/spring/application/boot.rb:19:in '<top (required)>'
from */ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
from */ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
from -e:1:in '<main>'
```
this happens on clean rails 5 app

**Comment by yahonda** [comment]
Thanks for using Oracle enhanced adapter with Rails 5.

Update Gemfile to add this entry, then it should address these errors.
```ruby
gem 'activerecord-oracle_enhanced-adapter', :github => 'activerecord-oracle_enhanced-adapter', :branch => 'rails5'
```

Rails 5 support is work in progress, have not pushed to rubygems yet.

**Comment by thiaguerd** [comment]
ok man, thanks!

**Comment by yahonda** [comment]
If the previous gemfile entry not working, please try this one:

```ruby
  gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'rails5'
```

**Comment by thiaguerd** [comment]
I noted this
but i am using

```ruby
gem 'activerecord-oracle_enhanced-adapter', git: 'git@github.com:rsim/oracle-enhanced.git', branch: 'rails5'
```

thanks for you attention :+1:

**Comment by yahonda** [comment]
Great, closing this since it has been resolved.
