### ISSUE TITLE
ruby 2.3.1@rails5 Cursor was already closed

### ISSUE THREAD

**Issue by thiaguerd** [rsim/oracle-enhanced#984]
``` bash
ActiveRecord::StatementInvalid: OCIException: OCI8::Cursor was already closed.: SELECT ....
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:516:in `attr_get_ub4'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:516:in `define_columns'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/ruby-oci8-2.2.2/lib/oci8/cursor.rb:127:in `exec'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/activerecord-oracle_enhanced-adapter-1.7.0/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:164:in `exec'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/activerecord-oracle_enhanced-adapter-1.7.0/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:39:in `block in exec_query'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /usr/lo
 cal/rvm/gems/ruby-2.3.1@rails5/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/activerecord-oracle_enhanced-adapter-1.7.0/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1266:in `log'
    /usr/local/rvm/gems/ruby-2.3.1@rails5/gems/activerecord-oracle_enhanced-adapter-1.7.0/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:22:in `exec_query'
```

``` ruby
Thread.new do
    c = ActiveRecord::Base.establish_connection(:hml)
    r =  c.connection.exec_query(@sql).to_a
    process_result r
end
```

**Comment by thiaguerd** [comment]
i try

````ruby
c.connection.reconnect! unless c.connection.active?
````

before exec_query but the same happens
this Thread run each hour
only first time works

**Comment by mlh758** [comment]
This is something I'm running into still as well. 
```
ActiveRecord::StatementInvalid: OCIException: OCI8::Cursor was already closed.: select distinct...
```

We're using Ruby 2.4.1, Ruby OCI8 2.2.3, Oracle Enhanced Adapter 1.6.9

This generally occurs whenever we are running a SQL statement with exec_query from ActiveJob, and another job starts up and runs a query as well.
